### Programming for Biomedical Informatics
#### Week 9 - Functional Analysis Using Ontologies

Ontologies are commonly used to aid interpretation of molecular data, most commonly through use of functional annotations to genes and proteins using the Gene Onotlogy combined with downstream likelihood/enrichment analysis using tools such as GSEA as we have discussed. Ontologies are also used in strategies to align unstructured data with domains, for example looking for words and/or phrases that can be mapped to classes in ontologies. Examples here would include things like looking for terms associated with clinical terminolgies in patient discharge summaries.

In this notebook we will perform some basic phenotype extraction from publication abstracts, attempting to find examples of HPO terms that are associated with mentions of particular diseases.

To do this we will randomly select 1000 papers from PubMed that are tagged with the MeSH Major Topic "Autism Spectrum Disorder" retreive their titles and abstracts and then search for phenotypes and genes.

In [16]:
'''
we're going to use a biomedical named entity recognition model called en_core_sci_sm which is a model developed by the Allen Institute for biomedical text processing
https://allenai.github.io/scispacy/
'''

# %pip install scispacy
# %pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_sm-0.5.4.tar.gz

"\nwe're going to use a biomedical named entity recognition model called en_core_sci_sm which is a model developed by the Allen Institute for biomedical text processing\nhttps://allenai.github.io/scispacy/\n"

In [17]:
# Setup for NLP

import pandas as pd
import spacy
from scispacy.linking import EntityLinker
from scispacy.abbreviation import AbbreviationDetector

# supress warnings
import warnings
warnings.filterwarnings('ignore')

## SciSpacy:
- The website shows what entities in biomedical data the transformer model has been trained on
- In Disease, it will have seen text that is used to describe them e.g. learned to assosiate entities and synonyms 
- Sci spaCy tells that a bit of text is a gene, not what gene it is
- You need to normalise to the gene name from that text
- The UMLS entity linker then goes on from that text to link to the UMLS to get the gene name

In [ ]:
'''when this is first run it will download some large data files to perform the UMLS linking
approx 2GB in total. On subsequent rune the model will take about 1 minute to load'''

# load the model
nlp = spacy.load("en_core_sci_sm"); # Not restricted to biomedical data, but in fine tuning it has seen biomedial data

# add abbreviations detector
nlp.add_pipe("abbreviation_detector"); # adding a modules here to deal with abbreviations, this adds ability to disambiguate abreviations from base model

# add UMLS entity-linker
nlp.add_pipe("scispacy_linker", config={"resolve_abbreviations": True,"linker_name": "umls","filter_for_definitions": False});
# This module is a linker, once this is

In [ ]:
# let's look at a simple example to understand this, this is an abstract from a paper. What concepts live in this abstract
queryText = 'PAX6 and GLI3 is a highly conserved transcription factor that plays a critical role in eye development in all animals. Mutations in the PAX6 gene are associated with aniridia, a congenital eye malformation characterized by the absence of the iris and other eye abnormalities.'

concepts = dict()

try:
    #perform nlp
    doc = nlp(queryText) # scispacy object, this returns a string of objects
    for entity in doc.ents:
        link = concept,score = entity._.kb_ents[0]
        concepts[entity.text] = concept
        print(entity.text, concept, score)
except:
    #case of no text
    pass


### This shows that Pax6 was linked to that number, these links are UMLS accession key
# You could chose only the child terms of genes in the UMLS ontology, and throw away the UMLS accessions not related to this

PAX6 C1418276 0.9495171904563904
GLI3 C0082708 0.9556154608726501
eye development C1517080 0.9721701741218567
animals C0003062 0.973741888999939
Mutations C0026882 0.9732257723808289
PAX6 gene C1418276 0.893574059009552
associated with C0332281 0.9891291856765747
aniridia C0003076 0.9635230302810669
congenital eye malformation C0015393 0.9502196311950684
characterized C1880022 0.9680080413818359
absence C0332197 0.9857189655303955
iris C0022077 0.9765904545783997
eye abnormalities C0015393 0.9852664470672607

In [20]:
# the human phenotype ontology contains database_cross_reference entries that include the UMLS concept id
# we can use this to link the HPO terms to the UMLS concepts

# load the HPO data using pronto
import pronto

# load the HPO ontology
# fetch the Human Phenotype Onology OBO file and parse it with pronto

# download the HPO ontology OBO file
import urllib.request

current_hpo_url = 'http://purl.obolibrary.org/obo/hp.obo'

# download the file
urllib.request.urlretrieve(current_hpo_url,'hpo.obo');

# parse the file
hpo = pronto.Ontology('hpo.obo')

In [ ]:
# we can look in the xrefs (sic. cross-references) of a term to find the UMLS concept id
# This is a link out from Gene Phenotype Ontology 
# FOr every concept found, I know its a human phenotype terms
# I can link between human phenotype term to UMLS terms
def hpo2concept(hpo_id):
    term = hpo[hpo_id]
    xrefs = [xref.id for xref in term.xrefs]
    try:
        umls_id = [xref for xref in xrefs if xref.startswith('UMLS')][0].split(':')[1]
        return umls_id
    except:
        return None

# let's test this function
hpo2concept('HP:0001695')

'C0018790'

In [22]:
# we're now going to brute force the conversion of all HPO terms to UMLS concepts
hpo2umls = {term.id:hpo2concept(term.id) for term in hpo.terms()}

In [23]:
# look at the first 10 entries
list(hpo2umls.items())[:10]

[('HP:0000001', 'C0444868'),
 ('HP:0000002', 'C4025901'),
 ('HP:0000394', 'C0266614'),
 ('HP:0000395', 'C1845272'),
 ('HP:0000396', 'C1837731'),
 ('HP:0000399', 'C4021806'),
 ('HP:0000400', 'C1835581'),
 ('HP:0000402', 'C0395837'),
 ('HP:0000403', 'C0747085'),
 ('HP:0000405', 'C0018777')]

In [36]:
#lets see if any of the CUIs from our test sentence have been mapped to HPO terms
for entity in concepts.keys():
    concept = concepts[entity]
    if concept in hpo2umls.values():
        print(entity, concept, [hpo[k] for k,v in hpo2umls.items() if v == concept])

aniridia C0003076 [Term('HP:0000526', name='Aniridia')]
congenital eye malformation C0015393 [Term('HP:0000478', name='Abnormality of the eye')]
eye abnormalities C0015393 [Term('HP:0000478', name='Abnormality of the eye')]

In [25]:
'''
As a niche example (not a mainstream ontology) we will look at the ASDPTO ontology which
has been developed as a custom ontology for autism spectrum disorder.

For every term in the ASDPTO ontology, we will look for UMLS concepts.

NB we are limited to the work done by ASDPTO curators in adding annotations to the terms
'''

current_asdpto_url = 'https://data.bioontology.org/ontologies/ASDPTO/submissions/1/download?apikey=4a2fbff0-ef88-432e-b1a1-dffc07e71146'

# download the file
urllib.request.urlretrieve(current_asdpto_url,'autism.obo');

# parse the file
autism  = pronto.Ontology('autism.obo')

In [26]:
# function to find the UMLS concept for a term in ASDPTO
def find_concept(term):
    for annotation in term.annotations:
        try:
            # if the string contains a cui= then it is a UMLS concept
            # extract the CUI
            if 'cui=' in annotation.resource:
                #split the string on 'cui=' and take the remainder
                concept = annotation.resource.split('cui=')[1]
                return(concept)
        except:
            pass

# we can now use this function to find the UMLS concept for each term in the ASDPTO ontology
asdpto2umls = {term.name:find_concept(term) for term in autism.terms()}

# remove any None entries
asdpto2umls = {k:v for k,v in asdpto2umls.items() if v is not None}

# print how many terms have been mapped to UMLS concepts
print(f'There are ',len(asdpto2umls),' terms in the ASDPTO ontology that have been mapped to UMLS concepts')

# look at the first 10 entries
list(asdpto2umls.items())[:10]

There are  82  terms in the ASDPTO ontology that have been mapped to UMLS concepts

[('Psychiatric Hospitalization', 'C0748061'),
 ('Ability to Convey Feelings', 'C1821397'),
 ('Gross Motor Skills', 'C0678858'),
 ('Perinatal Exposures', 'C1531967'),
 ('Use of Free Time', 'C0517871'),
 ('Depression', 'C0011570'),
 ('Medical History', 'C0262926'),
 ('Social Anxiety', 'C0424166'),
 ('Newborn Exposures', 'C0920206'),
 ('Adherence to Rules in the Home', 'C0562410')]

In [27]:
'''Now that we have all the NLP components in place to identify and map HPO terms let's now fetch the data and perform the analysis'''

"Now that we have all the NLP components in place to identify and map HPO terms let's now fetch the data and perform the analysis"

In [28]:
# let's use our knowledge of eUtils to fetch the raw material for our analysis
# we will use the requests library to fetch the data using the eUtils API
# we will use the xml library to parse the data

import urllib.request
import xml.etree.ElementTree as ET

# load my API key from the file
with open('../../bio_api_keys/ncbi.txt', 'r') as file:
    api_key = file.read().strip()

with open('../../bio_api_keys/ncbi_email.txt', 'r') as file:
    email = file.read().strip()

pubmed_query = '"Autism Spectrum Disorder[Majr]"'

# Define the parameters for the eSearch request
esearch_params = {
    'db': 'pubmed',
    'term': pubmed_query,
    'api_key': api_key,
    'email': email,
    'usehistory': 'y'
}

# encode the parameters so they can be passed to the API
encoded_data = urllib.parse.urlencode(esearch_params).encode('utf-8')

# the base request url for eSearch
url = f"https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"

# make the request
request = urllib.request.Request(url, data=encoded_data)
response = urllib.request.urlopen(request)

# read into an XML object
esaerch_data_XML = ET.fromstring(response.read())

# print the number of results
count = esaerch_data_XML.find('Count').text
print(f'Total number of results: {count}')

# Extract WebEnv and QueryKey
webenv = esaerch_data_XML.find('WebEnv').text
query_key = esaerch_data_XML.find('QueryKey').text

efetch_params = {
'db': 'pubmed',
'query_key': query_key,
'WebEnv': webenv,
'retmax': '1000',
'api_key': api_key,
'email': email
}

# encode the parameters so they can be passed to the API
encoded_data = urllib.parse.urlencode(efetch_params).encode('utf-8')

# the base request url for eSearch
url = f"https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"

# make the request
request = urllib.request.Request(url, data=encoded_data)
response = urllib.request.urlopen(request)

# read into an XML object
efetch_data_XML = ET.fromstring(response.read())

# let's look at the first 10 articles
for article in efetch_data_XML.findall('.//PubmedArticle')[:10]:
    pmid = article.find('.//PMID').text
    title = article.find('.//ArticleTitle').text
    abstract = article.find('.//AbstractText').text
    print(f'{pmid}: {title}')
    print(f'Abstract: {abstract}')

Total number of results: 45121
41226513: Urinary Uremic Toxin Signatures and the Metabolic Index of Gut Dysfunction (MIGD) in Autism Spectrum Disorder: A Stool-Phenotype-Stratified Analysis.
Abstract: Gut-derived uremic toxins may play a key role in neurodevelopmental conditions such as autism spectrum disorder (ASD) via host-microbe metabolic interactions. We evaluated five uremic toxins-p-cresyl sulfate (PCS), indoxyl sulfate (IS), trimethylamine N-oxide (TMAO), asymmetric dimethylarginine (ADMA), and symmetric dimethylarginine (SDMA)-in urine samples of 97 children with ASD and 71 neurotypical controls, stratified by Bristol Stool Chart (BSC) consistency types. Four of these toxins (PCS, IS, TMAO, ADMA) were integrated into a novel composite biomarker called the Metabolic Index of Gut Dysfunction (MIGD), while SDMA was measured as a complementary renal function marker. While individual metabolite levels showed no statistically significant differences, group-wise analysis by stool phenotype revealed distinct trends. ASD children with hard stools (BSC 1-2) showed elevated PCS levels and the MIGD score (median 555.3), reflecting phenolic fermentation dominance with reduced indolic detoxification. In contrast, children with loose stools (BSC 6-7) had the lowest MIGD values (median 109.8), driven by higher IS and lower ADMA concentrations, suggestive of enhanced indole metabolism. These findings indicate that MIGD may serve as a novel biomarker to stratify metabolic phenotypes in ASD, linking urinary metabolite patterns to gut function. Further validation in larger and longitudinal cohorts is warranted to confirm its potential utility in precision microbiota-targeted interventions.
41224750: Anticipation of a therapeutic odyssey following predictive testing for autism.
Abstract: Brain-based tools are being developed to identify infants at ultra-high likelihood for developing autism and enable presymptomatic intervention, though such interventions are not yet clinically available. Given persistent challenges in accessing autism services, we sought to understand how families might use early predictive results to seek support. We analyzed 55 interviews with parents of infants aged 6-13 months; one group had experience parenting an older autistic child (n = 30), the other had no prior autism parenting experience (n = 25). All parents were asked what steps they would take if told their infant was likely to develop autism. Both groups described an intent to find appropriate services; parents with prior autism experience provided more specifics based on prior knowledge. The groups diverged in their anticipated supports and information sources. Parents with autism experience anticipated seeking financial support via insurance and disability benefits; those without autism experience reported they would consult their pediatrician for information or search online. This qualitative study was conducted with a sample of parents selected for their specific life experiences, but likely does not capture the full range of potential responses to biomarker testing in infancy. Given that most services and benefits require a formal diagnosis, families receiving predictive results in infancy will likely face challenges finding appropriate services. Prior to implementing predictive testing in the first year of life, researchers should consider their obligation to support families who receive predictive results.
41224335: Autism spectrum disorder in Saudi Arabia: Clinical dynamics from a multi-center study.
Abstract: Autism Spectrum Disorder (ASD) is a neurodevelopmental condition characterized by impairments in communication, social interaction, and behavior. This study aimed to explore the factors influencing the clinical presentation of children with ASD in Saudi Arabia, focusing on demographic, medical, and environmental determinants.
41221243: The sequential mediating roles of alexithymia and interpersonal problems in the relationship between autistic traits and suicidal ideation: evidence from Chinese college students.
Abstract: Although prior studies suggested that higher levels of autistic traits correlated with more suicidal thoughts and behavior, the specific underlying mechanism was not clear. The present study was designed to expand prior findings and test the mediating roles of alexithymia and interpersonal problems on the relation between autistic traits and suicidal ideation among large population-based college samples.
41220090: Fingolimod Exerts Therapeutic Effects on Autistic Mice via Improving the Structure and Function of Meningeal Lymphatics.
Abstract: Accumulating evidence suggests a correlation between maternal infection during pregnancy and an increased risk of autism spectrum disorder (ASD) in offspring. Our previous studies have demonstrated that maternal immune activation (MIA) induces autism-like behaviors in offspring mice, accompanied by significant lateral ventricular enlargement and cerebrospinal fluid (CSF) circulation deficits. As a critical pathway for CSF drainage, the role of meningeal lymphatic vessels in the pathophysiology of ASD remains uncharacterized. Fingolimod (FTY720), a clinically used immunomodulator, has been shown to ameliorate autism-like behaviors, but its underlying mechanism remains unclear.
41220017: Prenatal fluoride exposure and autistic behaviors in preschool-aged children: the Maternal-Infant Research on Environmental Chemicals (MIREC) cohort study.
Abstract: The prevalence of autism spectrum disorder has risen in recent decades. Given the growing evidence that prenatal fluoride exposure may be neurotoxic, we examined associations between prenatal fluoride exposure and parent-reported autistic behaviors in preschool-aged children.
41218771: Motor organisation of social play in children with autism.
Abstract: Play is a quintessential human behaviour, underpinned by motor organisation and fundamental for learning and development. However, the motor patterns underlying play have not been computationally characterised in children with autism, despite known play pattern differences, including reduced social and pretend play. Recent evidence of fundamental neuromotor disruption in autism suggests neuromotor organisation differences may underpin play differences. We employed a digital game to examine play patterns in 878 children aged 2.5-6 years old, including 372 diagnosed with autism spectrum disorders (ASD), 64 diagnosed with other neurodevelopmental disorders and 441 without known neurodevelopmental problems (WP). Computational characterisation of play patterns by network analysis revealed significant differences between groups in the motor organisation of its sequential steps. Children with ASD developed an indirect, two-step pattern during the social food-sharing aspect of the game, in contrast to a direct, single-step pattern by WP children. These findings provide new variables for the digital characterisation of ASD. They reveal differences in the sequential nature of goal-directed motor organisation made in play in autism that precede higher-order differences in social cognition and emotional regulation reported in the literature, giving important insight into the psychomotor nature of autism for its education, care and support.
41208677: Entanglements and Absences: Mental Health in Narratives of Neurodiversity.
Abstract: This commentary discusses the relationship between neurodiversity and mental health across twelve narratives shared by people with lived experiences of neurodivergence, mainly autism and attention deficit hyperactivity disorder (ADHD). Many authors in this symposium describe the psychological distress they endure as the product of ableism against neurodivergent people, calling us to reflect upon the entangled nature of neurodevelopmental conditions and mental health conditions. Absent in this issue are stories of people whose sole or primary experience of neurodivergence is a mental health condition like bipolar or schizophrenia, and I reflect here on what such missing narratives could teach us about neurodiversity, mental health, and disability.
41208675: Embracing Neurodiversity.
Abstract: This commentary discusses the complexities of neurodivergence and the struggles faced by neuro-divergent individuals and their families. Reflecting on narratives from the journal Narrative Inquiry in Bioethics, I examine the challenges of understanding, acceptance, and advocating for people who are neurodiverse within a neurotypical society. I address such issues as misdiagnosis, lack of diagnosis, and the harmful effects of masking behaviors. I also touch on controversial treatments like Applied Behavior Analysis (ABA), noting its acceptance by many professionals who work with autistic people, but also its criticisms from members of the autism community. I stress the importance of embracing neurodiversity for the health and resilience of society and argue that diversity in nature and human cognition promotes adaptation and survival. Lastly, I highlight the need to remove barriers to healthcare and therapy, support responsible research, encourage continuing education for professionals, and foster neurodiverse relationships. By honoring and protecting diversity, we can strengthen our communities and improve the human experience for everyone.
41207796: Maternal paracetamol (acetaminophen) use during pregnancy and risk of autism spectrum disorder and attention deficit/hyperactivity disorder in offspring: umbrella review of systematic reviews.
Abstract: To assess the quality, biases, and validity of evidence on maternal paracetamol (acetaminophen) use during pregnancy and the risk of autism spectrum disorder (referred to as autism) and attention deficit/hyperactivity disorder (ADHD) in offspring.

In [ ]:
# for each article check whether it has an abstract and a title
# if it does combine the title and abstract into a single string
# if it doesn't remove it from the list
articles = dict()

for article in efetch_data_XML.findall('.//PubmedArticle'):
    try:
        pmid = article.find('.//PMID')
        title = article.find('.//ArticleTitle')
        abstract = article.find('.//AbstractText')
        tiab = title.text + ' ' + abstract.text
        articles[pmid.text] = tiab
    except:
        pass

print(f'Number of articles with abstracts: {len(articles)}') # 27 of these don't have abstracts

Number of articles with abstracts: 973

In [ ]:
# lets write a function based on code above to perform ner on articles and return
def nlp_article(article):

    current_article_concepts = dict()

    try:
        #perform nlp
        doc = nlp(article)
        for entity in doc.ents:
            link = concept,score = entity._.kb_ents[0]
            current_article_concepts[entity.text] = concept
    except:
        #case of no text
        pass

    ### We have now found the entities, and we need to check for a link

    hpo_terms = []

    for entity in current_article_concepts.keys():
        concept = current_article_concepts[entity]
        if concept in hpo2umls.values():
            print(entity, concept, [hpo[k] for k,v in hpo2umls.items() if v == concept])
            current_hpo = [hpo[k] for k,v in hpo2umls.items() if v == concept]
            hpo_terms.append(current_hpo[0].id)
    return list(set(hpo_terms))

In [ ]:
# now we can apply this function to all the articles
articles_hpo = {pmid: nlp_article(article) for pmid, article in articles.items()}

### We are not sure the importance of the references, just that they occur

autism C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
Autistic Mice C0004352 [Term('HP:0000717', name='Autism')]
autism-like behaviors C0856975 [Term('HP:0000729', name='Autistic behavior')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
attention deficit hyperactivity disorder C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
ADHD C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
attention deficit/hyperactivity disorder C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autistic adults C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
autistic brain C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Gestational diabetes C0085207 [Term('HP:0009800', name='Maternal diabetes')]
Stage-Dependent C1835978 [Term('HP:0003831', name='Typified by age-related disease onset')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
autistic behaviors C0856975 [Term('HP:0000729', name='Autistic behavior')]
major C0205082 [Term('HP:0012828', name='Severe')]
Autistic behaviors C0856975 [Term('HP:0000729', name='Autistic behavior')]
Autistic C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
Autistic C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
neurological abnormalities C0497552 [Term('HP:0000707', name='Abnormality of the nervous system')]
Welsh autism C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
Autistic people C0004352 [Term('HP:0000717', name='Autism')]
progressive C0205329 [Term('HP:0003676', name='Progressive')]
Autism Risk C0004352 [Term('HP:0000717', name='Autism')]
autism risk C0004352 [Term('HP:0000717', name='Autism')]
ECHO Autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
Autistic Adults C0004352 [Term('HP:0000717', name='Autism')]
Anorexia C0003123 [Term('HP:0002039', name='Anorexia')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
Schizophrenia C0036341 [Term('HP:0100753', name='Schizophrenia')]
Dysphagia C0011168 [Term('HP:0002015', name='Dysphagia')]
dysphagia C0011168 [Term('HP:0002015', name='Dysphagia')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Mitochondrial dysfunction C4021734 [Term('HP:0003287', name='Abnormality of mitochondrial metabolism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Autistic Adults C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
central C0205099 [Term('HP:0030645', name='Central')]
Broad Autism C0004352 [Term('HP:0000717', name='Autism')]
behavioral symptoms C0004941 [Term('HP:0000708', name='Atypical behavior')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
peripheral C0205100 [Term('HP:0030646', name='Peripheral')]
autoimmune diseases C0004364 [Term('HP:0002960', name='Autoimmunity')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Autistic C0004352 [Term('HP:0000717', name='Autism')]
autism centers C0205099 [Term('HP:0030645', name='Central')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autistic adults C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
AUTISM C0004352 [Term('HP:0000717', name='Autism')]
Autistic C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
Autistic C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
autism-like behaviors C0856975 [Term('HP:0000729', name='Autistic behavior')]
B-cell lymphoma 2 C0079731 [Term('HP:0012191', name='B-cell lymphoma')]
Bcl-2 C0079731 [Term('HP:0012191', name='B-cell lymphoma')]
Oppositional Defiant C0029121 [Term('HP:0010865', name='Oppositional defiant disorder')]
Oppositional Defiant Disorder C0029121 [Term('HP:0010865', name='Oppositional defiant disorder')]
ODD C0029121 [Term('HP:0010865', name='Oppositional defiant disorder')]
autistic adults C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
encephalopathy C0085584 [Term('HP:0001298', name='Encephalopathy')]
intellectual disability C3714756 [Term('HP:0001249', name='Intellectual disability')]
seizures C0036572 [Term('HP:0001250', name='Seizure')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
moderate C0205081 [Term('HP:0012826', name='Moderate')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
ADHD C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
attention-deficit/hyperactivity disorder C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
globally C0205246 [Term('HP:0012837', name='Generalized')]
Gestational diabetes mellitus C0085207 [Term('HP:0009800', name='Maternal diabetes')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
poor eye contact C1445953 [Term('HP:0000817', name='Reduced eye contact')]
psychosis C0033975 [Term('HP:0000709', name='Psychosis')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
psychotic disorders C0033975 [Term('HP:0000709', name='Psychosis')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Autistic C0004352 [Term('HP:0000717', name='Autism')]
schizophrenia C0036341 [Term('HP:0100753', name='Schizophrenia')]
autistic adults C0004352 [Term('HP:0000717', name='Autism')]
Autistic Adults C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
ADHD C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
Attention-Deficit Hyperactivity Disorder C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
Immune Dysregulation C1844666 [Term('HP:0002958', name='Immune dysregulation')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
congenital abdominal wall defects C0238577 [Term('HP:0010866', name='Abdominal wall defect')]
abdominal wall defect C0238577 [Term('HP:0010866', name='Abdominal wall defect')]
AWD C0238577 [Term('HP:0010866', name='Abdominal wall defect')]
omphalocele C0795690 [Term('HP:0001539', name='Omphalocele')]
gastroschisis C0265706 [Term('HP:0001543', name='Gastroschisis')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autistic people C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
behavioral symptoms C0004941 [Term('HP:0000708', name='Atypical behavior')]
ASD C0018817 [Term('HP:0001631', name='Atrial septal defect')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
mild intellectual disability C0026106 [Term('HP:0001256', name='Mild intellectual disability')]
CP-localized C0392752 [Term('HP:0012838', name='Localized')]
autistic adults C0004352 [Term('HP:0000717', name='Autism')]
attention-deficit/hyperactivity disorder C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
ADHD C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
center of C0205099 [Term('HP:0030645', name='Central')]
Autistic adults C0004352 [Term('HP:0000717', name='Autism')]
autistic people C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
ADHD C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
autism C0004352 [Term('HP:0000717', name='Autism')]
attention-deficit/hyperactivity disorder C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
Intensity Variables C0522510 [Term('HP:0012824', name='Severity')]
Autistic C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
Mitochondrial dysfunction C4021734 [Term('HP:0003287', name='Abnormality of mitochondrial metabolism')]
peripheral tissues C0205100 [Term('HP:0030646', name='Peripheral')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Autistic C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
Autistic C0004352 [Term('HP:0000717', name='Autism')]
attention deficit hyperactivity disorder C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
attention-deficit/hyperactivity disorder C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
ADHD C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
ASD+ADHD C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autistic people C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
intellectual disability-associated genes C3714756 [Term('HP:0001249', name='Intellectual disability')]
autism C0004352 [Term('HP:0000717', name='Autism')]
nutritional deficiencies C0162429 [Term('HP:0004395', name='Malnutrition')]
autism C0004352 [Term('HP:0000717', name='Autism')]
spastic paraparesis C0037771 [Term('HP:0002313', name='Spastic paraparesis')]
autistic adults C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
moderate C0205081 [Term('HP:0012826', name='Moderate')]
Autisme C0004352 [Term('HP:0000717', name='Autism')]
cardiorespiratory impacts C0600228 [Term('HP:0006543', name='Cardiorespiratory arrest')]
ASD C0018817 [Term('HP:0001631', name='Atrial septal defect')]
Autistic C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
ADHD C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
attention-deficit/hyperactivity disorder C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
Gestational Diabetes C0085207 [Term('HP:0009800', name='Maternal diabetes')]
Polycystic Ovary Syndrome C0032460 [Term('HP:0000147', name='Polycystic ovaries')]
PCOS C0032460 [Term('HP:0000147', name='Polycystic ovaries')]
gestational diabetes C0085207 [Term('HP:0009800', name='Maternal diabetes')]
GD C0085207 [Term('HP:0009800', name='Maternal diabetes')]
polycystic ovary syndrome C0032460 [Term('HP:0000147', name='Polycystic ovaries')]
autism C0004352 [Term('HP:0000717', name='Autism')]
peripheral tissues C0205100 [Term('HP:0030646', name='Peripheral')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
global C0205246 [Term('HP:0012837', name='Generalized')]
intellectual disabilities C3714756 [Term('HP:0001249', name='Intellectual disability')]
macrocephaly C0221355 [Term('HP:0001355', name='Megalencephaly')]
ADHD C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
attention-deficit/hyperactivity disorder C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
Autistic C0004352 [Term('HP:0000717', name='Autism')]
Autistic C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
AUT C0004352 [Term('HP:0000717', name='Autism')]
celiac disease C0007570 [Term('HP:0002608', name='Celiac disease')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
global C0205246 [Term('HP:0012837', name='Generalized')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Autistic C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autism group C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
Obesity C0028754 [Term('HP:0001513', name='Obesity')]
ADHD C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
Attention-deficit/hyperactivity disorder C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autism genes C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
moderates C0205081 [Term('HP:0012826', name='Moderate')]
autistic behavior C0856975 [Term('HP:0000729', name='Autistic behavior')]
attention-deficit hyperactivity disorder C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
attention-deficit/hyperactivity disorder C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
ADHD C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
autistic adults C0004352 [Term('HP:0000717', name='Autism')]
Autistic C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Autistic C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
gestational diabetes C0085207 [Term('HP:0009800', name='Maternal diabetes')]
autistic behavior C0856975 [Term('HP:0000729', name='Autistic behavior')]
Gestational diabetes mellitus C0085207 [Term('HP:0009800', name='Maternal diabetes')]
GDM C0085207 [Term('HP:0009800', name='Maternal diabetes')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
globally C0205246 [Term('HP:0012837', name='Generalized')]
autistic life C0004352 [Term('HP:0000717', name='Autism')]
globally C0205246 [Term('HP:0012837', name='Generalized')]
Sleep disturbances C0037317 [Term('HP:0002360', name='Sleep disturbance')]
Self-Injury C0085271 [Term('HP:0100716', name='Self-injurious behavior')]
self-injurious behaviors C0085271 [Term('HP:0100716', name='Self-injurious behavior')]
autism C0004352 [Term('HP:0000717', name='Autism')]
ASD C0018817 [Term('HP:0001631', name='Atrial septal defect')]
ASD C0018817 [Term('HP:0001631', name='Atrial septal defect')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
nonautistic C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
autistic people C0004352 [Term('HP:0000717', name='Autism')]
ASD C0018817 [Term('HP:0001631', name='Atrial septal defect')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
moderate C0205081 [Term('HP:0012826', name='Moderate')]
severe C0205082 [Term('HP:0012828', name='Severe')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Autistic Adults C0004352 [Term('HP:0000717', name='Autism')]
autistic adults C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Peripheral C0205100 [Term('HP:0030646', name='Peripheral')]
immune dysregulation C1844666 [Term('HP:0002958', name='Immune dysregulation')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
dyspraxia C0003635 [Term('HP:0002186', name='Apraxia')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
blindness C0456909 [Term('HP:0000618', name='Blindness')]
autism risk C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autism cohort C0004352 [Term('HP:0000717', name='Autism')]
Autistic C0004352 [Term('HP:0000717', name='Autism')]
Autistic C0004352 [Term('HP:0000717', name='Autism')]
Schizophrenia C0036341 [Term('HP:0100753', name='Schizophrenia')]
autism C0004352 [Term('HP:0000717', name='Autism')]
itch C0033774 [Term('HP:0000989', name='Pruritus')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Attention-Deficit/Hyperactivity Disorder C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
attention-deficit/hyperactivity disorder C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
ADHD C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
attention-deficit/hyperactivity disorder C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
ASD C0018817 [Term('HP:0001631', name='Atrial septal defect')]
ADHD C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
autism C0004352 [Term('HP:0000717', name='Autism')]
peripheral C0205100 [Term('HP:0030646', name='Peripheral')]
peripheral BDNF C0205100 [Term('HP:0030646', name='Peripheral')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Autism C0004352 [Term('HP:0000717', name='Autism')]
ADHD C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
autism C0004352 [Term('HP:0000717', name='Autism')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
ADHD C1263846 [Term('HP:0007018', name='Attention deficit hyperactivity disorder')]
ASD C0018817 [Term('HP:0001631', name='Atrial septal defect')]
autistic C0004352 [Term('HP:0000717', name='Autism')]
sleep disturbances C0037317 [Term('HP:0002360', name='Sleep disturbance')]

In [ ]:
# let's look at the results from the first 10 articles
list(articles_hpo.items())[:10]

# what percentage of articles have HPO terms
articles_with_hpo = [k for k,v in articles_hpo.items() if v]
print(f'Percentage of articles with HPO terms: {len(articles_with_hpo)/len(articles)*100:.2f}%')

## It may not be the case that phenotype terms may be in the paper at all e.g. purely molecular, or our system misses things

Percentage of articles with HPO terms: 37.20%

In [ ]:
# find the unique HPO terms found in the articles
unique_hpo_terms = list(set([term for terms in articles_hpo.values() for term in terms]))

# create a dataframe to store the data
df = pd.DataFrame(index=articles.keys(), columns=unique_hpo_terms)

# fill the dataframe
for pmid, terms in articles_hpo.items():
    df.loc[pmid, terms] = 1

# fill the NaN values with 0
df.fillna(0, inplace=True)

# print the first 5 rows
df.head()

## Their are cpu efficient ways to deal with the sparse matrices

,HP:0030858,HP:0000952,HP:0001256,HP:0002063,HP:0000709,HP:0004395,HP:0001355,HP:0030650,HP:0000729,HP:0002015,...,HP:0002186,HP:0000938,HP:0002119,HP:0030646,HP:0012532,HP:0000618,HP:0007302,HP:0004905,HP:0012828,HP:0100753
41226513,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41224750,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41224335,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41221243,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41220090,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [34]:
# count the number of times each term appears and store this in a dataframe with columns
# 'HPO Term Name', 'HPO Term', 'Count' and sort by count
hpo_counts = df.sum().sort_values(ascending=False).reset_index()
hpo_counts.columns = ['HPO Term', 'Count']
hpo_counts['HPO Term Name'] = [hpo[term].name for term in hpo_counts['HPO Term']]

# use PrettyTable to display the data
from prettytable import PrettyTable

table = PrettyTable()
table.field_names = hpo_counts.columns
for row in hpo_counts.itertuples(index=False):
    table.add_row(row)
print(table)

+------------+-------+---------------------------------------------------+
|  HPO Term  | Count |                   HPO Term Name                   |
+------------+-------+---------------------------------------------------+
| HP:0000717 |  270  |                       Autism                      |
| HP:0007018 |   26  |      Attention deficit hyperactivity disorder     |
| HP:0001249 |   14  |              Intellectual disability              |
| HP:0001631 |   11  |                Atrial septal defect               |
| HP:0012837 |   9   |                    Generalized                    |
| HP:0000729 |   7   |                 Autistic behavior                 |
| HP:0030646 |   7   |                     Peripheral                    |
| HP:0012826 |   5   |                      Moderate                     |
| HP:0100753 |   5   |                   Schizophrenia                   |
| HP:0002958 |   4   |                Immune dysregulation               |
| HP:0009800 |   4   |                 Maternal diabetes                 |
| HP:0030645 |   4   |                      Central                      |
| HP:0100785 |   3   |                      Insomnia                     |
| HP:0012828 |   3   |                       Severe                      |
| HP:0002360 |   3   |                 Sleep disturbance                 |
| HP:0100716 |   3   |              Self-injurious behavior              |
| HP:0004905 |   2   |    Reduced circulating vitamin A concentration    |
| HP:0000708 |   2   |                 Atypical behavior                 |
| HP:0002180 |   2   |                 Neurodegeneration                 |
| HP:0000722 |   2   |                Compulsive behaviors               |
| HP:0003287 |   2   |      Abnormality of mitochondrial metabolism      |
| HP:0003676 |   2   |                    Progressive                    |
| HP:0000709 |   2   |                     Psychosis                     |
| HP:0002063 |   2   |                      Rigidity                     |
| HP:0002960 |   2   |                    Autoimmunity                   |
| HP:0000670 |   2   |                   Carious teeth                   |
| HP:0011163 |   2   | Focal sensory seizure with somatosensory features |
| HP:0000508 |   1   |                       Ptosis                      |
| HP:0006543 |   1   |              Cardiorespiratory arrest             |
| HP:0012758 |   1   |              Neurodevelopmental delay             |
| HP:0001250 |   1   |                      Seizure                      |
| HP:0012166 |   1   |                    Skin-picking                   |
| HP:0002313 |   1   |                Spastic paraparesis                |
| HP:0012532 |   1   |                    Chronic pain                   |
| HP:0012075 |   1   |                Personality disorder               |
| HP:0100602 |   1   |                    Preeclampsia                   |
| HP:0000147 |   1   |                 Polycystic ovaries                |
| HP:0012191 |   1   |                  B-cell lymphoma                  |
| HP:0001543 |   1   |                   Gastroschisis                   |
| HP:0007302 |   1   |             Bipolar affective disorder            |
| HP:0002186 |   1   |                      Apraxia                      |
| HP:0000938 |   1   |                     Osteopenia                    |
| HP:0002119 |   1   |                  Ventriculomegaly                 |
| HP:0000618 |   1   |                     Blindness                     |
| HP:0002608 |   1   |                   Celiac disease                  |
| HP:0030858 |   1   |                 Addictive behavior                |
| HP:0000707 |   1   |         Abnormality of the nervous system         |
| HP:0003831 |   1   |       Typified by age-related disease onset       |
| HP:0001256 |   1   |            Mild intellectual disability           |
| HP:0004395 |   1   |                    Malnutrition                   |
| HP:0001355 |   1   |                   Megalencephaly                  |
| HP:0030650 |   1   |                       Focal                       |
| HP:0002015 |   1   |                     Dysphagia                     |
| HP:0012768 |   1   |                 Neonatal asphyxia                 |
| HP:0010866 |   1   |               Abdominal wall defect               |
| HP:0000989 |   1   |                      Pruritus                     |
| HP:0001539 |   1   |                    Omphalocele                    |
| HP:0000545 |   1   |                       Myopia                      |
| HP:0000483 |   1   |                    Astigmatism                    |
| HP:0000817 |   1   |                Reduced eye contact                |
| HP:0001298 |   1   |                   Encephalopathy                  |
| HP:0002172 |   1   |                Postural instability               |
| HP:0030806 |   1   |                 Fast-growing nails                |
| HP:0002039 |   1   |                      Anorexia                     |
| HP:0000758 |   1   |     Abnormal nonverbal communicative behavior     |
| HP:0012832 |   1   |                     Bilateral                     |
| HP:0000577 |   1   |                     Exotropia                     |
| HP:0000005 |   1   |                Mode of inheritance                |
| HP:0010865 |   1   |           Oppositional defiant disorder           |
| HP:0000952 |   1   |                      Jaundice                     |
| HP:0012824 |   1   |                      Severity                     |
| HP:0011856 |   1   |                        Pica                       |
| HP:0001513 |   1   |                      Obesity                      |
| HP:0000540 |   1   |                   Hypermetropia                   |
| HP:0012838 |   1   |                     Localized                     |
+------------+-------+---------------------------------------------------+

## What have we done
- Loaded an ontology
- Queried pubmed, got back 45000
- Did entitiy recognition adn linking to UMLS
- Subsetted as phenotype
-

In [ ]:
# optional additional
### Gene to phenotype database captures information about disordereers:
# Global catalogue of rare genetic diseases:
import pandas as pd

# lets speciifically look at all the DDG2P papers fom PubMed
# read in the DDG2P data file
ddg2p = pd.read_csv('./DDG2P.csv')
ddg2p.head()

# get the list of unique PMIDs from the 'pmids' column
pmids = ddg2p['pmids'].str.split(';').explode().unique()

# how many unique PMIDs are there
print(f'Number of unique PMIDs: {len(pmids)}')

# randomly select 1000 of these
import random
random.seed(42)
pmids_sample = random.sample(list(pmids), 1000)

import urllib.request
import xml.etree.ElementTree as ET

# load my API key from the file
with open('../../bio_api_keys/ncbi.txt', 'r') as file:
    api_key = file.read().strip()

with open('../../bio_api_keys/ncbi_email.txt', 'r') as file:
    email = file.read().strip()

# fetch the data for these PMIDs
# Define the parameters for the eSearch request
esearch_params = {
    'db': 'pubmed',
    'id': ','.join(pmids_sample),
    'api_key': api_key,
    'email': email,
    'usehistory': 'y'
}

# encode the parameters so they can be passed to the API
encoded_data = urllib.parse.urlencode(esearch_params).encode('utf-8')

# the base request url for eSearch
url = f"https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"

# make the request
request = urllib.request.Request(url, data=encoded_data)
response = urllib.request.urlopen(request)

# read into an XML object
efetch_data_XML = ET.fromstring(response.read())

# for each article check whether it has an abstract and a title
# if it does combine the title and abstract into a single string
# if it doesn't remove it from the list
articles = dict()

for article in efetch_data_XML.findall('.//PubmedArticle'):
    try:
        pmid = article.find('.//PMID')
        title = article.find('.//ArticleTitle')
        abstract = article.find('.//AbstractText')
        tiab = title.text + ' ' + abstract.text
        articles[pmid.text] = tiab
    except:
        pass

print(f'Number of articles with abstracts: {len(articles)}')

# print the first 10 articles
for pmid, tiab in list(articles.items())[:10]:
    print(f'{pmid}: {tiab}')

Number of unique PMIDs: 6232
Number of articles with abstracts: 933
30809043: Evolutionary conserved networks of human height identify multiple Mendelian causes of short stature. Height is a heritable and highly heterogeneous trait. Short stature affects 3% of the population and in most cases is genetic in origin. After excluding known causes, 67% of affected individuals remain without diagnosis. To identify novel candidate genes for short stature, we performed exome sequencing in 254 unrelated families with short stature of unknown cause and identified variants in 63 candidate genes in 92 (36%) independent families. Based on systematic characterization of variants and functional analysis including expression in chondrocytes, we classified 13 genes as strong candidates. Whereas variants in at least two families were detected for all 13 candidates, two genes had variants in 6 (UBR4) and 8 (LAMA5) families, respectively. To facilitate their characterization, we established a clustered network of 1025 known growth and short stature genes, which yielded 29 significantly enriched clusters, including skeletal system development, appendage development, metabolic processes, and ciliopathy. Eleven of the candidate genes mapped to 21 of these clusters, including CPZ, EDEM3, FBRS, IFT81, KCND1, PLXNA3, RASA3, SLC7A8, UBR4, USP45, and ZFHX3. Fifty additional growth-related candidates we identified await confirmation in other affected families. Our study identifies Mendelian forms of growth retardation as an important component of idiopathic short stature.
23542699: Mutations in STAMBP, encoding a deubiquitinating enzyme, cause microcephaly-capillary malformation syndrome. Microcephaly-capillary malformation (MIC-CAP) syndrome is characterized by severe microcephaly with progressive cortical atrophy, intractable epilepsy, profound developmental delay and multiple small capillary malformations on the skin. We used whole-exome sequencing of five patients with MIC-CAP syndrome and identified recessive mutations in STAMBP, a gene encoding the deubiquitinating (DUB) isopeptidase STAMBP (STAM-binding protein, also known as AMSH, associated molecule with the SH3 domain of STAM) that has a key role in cell surface receptor-mediated endocytosis and sorting. Patient cell lines showed reduced STAMBP expression associated with accumulation of ubiquitin-conjugated protein aggregates, elevated apoptosis and insensitive activation of the RAS-MAPK and PI3K-AKT-mTOR pathways. The latter cellular phenotype is notable considering the established connection between these pathways and their association with vascular and capillary malformations. Furthermore, our findings of a congenital human disorder caused by a defective DUB protein that functions in endocytosis implicates ubiquitin-conjugate aggregation and elevated apoptosis as factors potentially influencing the progressive neuronal loss underlying MIC-CAP syndrome.
35607853: Biallelic variants in PAX3 cause Klein syndrome. Waardenburg syndrome is a group of genetic conditions that can cause hearing loss and pigmentation deficiency of the hair, skin, and eyes. Klein-Waardenburg syndrome (Waardenburg syndrome type 3) represents a distinct presentation of Waardenburg syndrome type 1 and includes musculoskeletal abnormalities in addition to dystopia canthorum hearing loss and pigmentary changes. Heterozygous or homozygous variants in the PAX3 gene cause Klein-Waardenburg syndrome. Here we report on a new severely affected child, with a homozygous PAX3 variant (c.251C>T; p.Ser84Phe), review the features of the syndrome, and propose a new classification. The designation of Waardenburg syndrome should be given only to patients with monoallelic pathogenic variants in PAX3 whether or not musculoskeletal abnormalities are present. Patients with biallelic PAX3 variants should be outlined as a distinct group and designated Klein syndrome.
16752401: High efficiency of mutation detection in type 1 stickler syndrome using a two-stage approach: vitreoretinal assessment coupled with exon sequencing for screening COL2A1. Stickler syndrome is a genetically heterogeneous disorder that affects the ocular, skeletal, and auditory systems. To date three genes, COL2A1, COL11A1, and COL11A2, encoding the heterotypic type II/XI collagen fibrils present in vitreous and cartilage have been shown to have mutations that result in Stickler syndrome. As systemic features in this disorder are variable we have used an ophthalmic examination to differentiate those patients with a membranous vitreous phenotype associated with mutations in COL2A1, from other patients who may have mutations in other genes. Gene amplification and exon sequencing was used to screen 50 families or sporadic cases with this membranous phenotype, for mutations in COL2A1. Mutations were detected in 47 (94%) cases consisting of 166 affected and 78 unaffected individuals. We also demonstrate that the predominantly ocular form of type 1 Stickler syndrome is not confined to mutations in the alternatively spliced exon 2. Using splicing reporter constructs we demonstrate that a mutant GC donor splice site in intron 51 can be spliced normally; this contributed to the predominantly ocular phenotype in the family in which it occurred.
19015483: A novel dominant mutation of the Nav1.4 alpha-subunit domain I leading to sodium channel myotonia. Mutations in SCN4A may lead to myotonia.
24607389: Mutations in USP9X are associated with X-linked intellectual disability and disrupt neuronal cell migration and growth. With a wealth of disease-associated DNA variants being recently reported, the challenges of providing their functional characterization are mounting. Previously, as part of a large systematic resequencing of the X chromosome in 208 unrelated families with nonsyndromic X-linked intellectual disability, we identified three unique variants (two missense and one protein truncating) in USP9X. To assess the functional significance of these variants, we took advantage of the Usp9x knockout mouse we generated. Loss of Usp9x causes reduction in both axonal growth and neuronal cell migration. Although overexpression of wild-type human USP9X rescued these defects, all three USP9X variants failed to rescue axonal growth, caused reduced USP9X protein localization in axonal growth cones, and (in 2/3 variants) failed to rescue neuronal cell migration. Interestingly, in one of these families, the proband was subsequently identified to have a microdeletion encompassing ARID1B, a known ID gene. Given our findings it is plausible that loss of function of both genes contributes to the individual's phenotype. This case highlights the complexity of the interpretations of genetic findings from genome-wide investigations. We also performed proteomics analysis of neurons from both the wild-type and Usp9x knockout embryos and identified disruption of the cytoskeleton as the main underlying consequence of the loss of Usp9x. Detailed clinical assessment of all three families with USP9X variants identified hypotonia and behavioral and morphological defects as common features in addition to ID. Together our data support involvement of all three USP9X variants in ID in these families and provide likely cellular and molecular mechanisms involved.
25464108: A Korean family with KBG syndrome identified by ANKRD11 mutation, and phenotypic comparison of ANKRD11 mutation and 16q24.3 microdeletion. KBG syndrome is a rare disease characterized by intellectual disability, typical craniofacial dysmorphism, macrodontia of the upper central incisors, short stature, and skeletal anomalies. Recently, ANKRD11 was identified as a gene that is responsible for the disease. In addition, microdeletion of 16q24.3, including ANKRD11, has been reported to result in the KBG syndrome phenotype. Herein, we discuss a Korean family with KBG syndrome, as identified by ANKRD11 gene mutation. The patients included a nine-month-old boy and his 21-month-old sister who failed to thrive and have delayed development. Chromosomal microarray was performed to identify the underlying genetic cause, but the results showed no abnormalities. However, the mother of the children was found to have features similar to her children. Therefore, we strongly suspected an autosomal-dominant inherited disease and performed whole exome sequencing. A mutation of ANKRD11 gene was found in all patients, and the frameshift variant c.2395-2398delAAAG was confirmed. Clinical manifestations of the patients were consistent with KBG syndrome. We reviewed all reported cases with confirmed ANKRD11 mutation or 16q24.3 microdeletion including ANKRD11. As a result, we conclude that severe short stature, intellectual disability, and macrodontia are the main characteristics in KBG syndrome related to ANKRD11 mutation.
28792876: NAD Deficiency, Congenital Malformations, and Niacin Supplementation. Congenital malformations can be manifested as combinations of phenotypes that co-occur more often than expected by chance. In many such cases, it has proved difficult to identify a genetic cause. We sought the genetic cause of cardiac, vertebral, and renal defects, among others, in unrelated patients.
25053765: TRMT10A dysfunction is associated with abnormalities in glucose homeostasis, short stature and microcephaly. Trm10 is a tRNA m(1)G9 methyltransferase, which in yeast modifies 12 different tRNA species, yet is considered non-essential for viability under standard growth conditions. In humans, there are three Trm10 orthologs, one mitochondrial and two presumed cytoplasmic. A nonsense mutation in one of the cytoplasmic orthologs (TRMT10A) has recently been associated with microcephaly, intellectual disability, short stature and adolescent onset diabetes.
35953447: Variants in the zinc transporter TMEM163 cause a hypomyelinating leukodystrophy. Hypomyelinating leukodystrophies comprise a subclass of genetic disorders with deficient myelination of the CNS white matter. Here we report four unrelated families with a hypomyelinating leukodystrophy phenotype harbouring variants in TMEM163 (NM_030923.5). The initial clinical presentation resembled Pelizaeus-Merzbacher disease with congenital nystagmus, hypotonia, delayed global development and neuroimaging findings suggestive of significant and diffuse hypomyelination. Genomic testing identified three distinct heterozygous missense variants in TMEM163 with two unrelated individuals sharing the same de novo variant. TMEM163 is highly expressed in the CNS particularly in newly myelinating oligodendrocytes and was recently revealed to function as a zinc efflux transporter. All the variants identified lie in highly conserved residues in the cytoplasmic domain of the protein, and functional in vitro analysis of the mutant protein demonstrated significant impairment in the ability to efflux zinc out of the cell. Expression of the mutant proteins in an oligodendroglial cell line resulted in substantially reduced mRNA expression of key myelin genes, reduced branching and increased cell death. Our findings indicate that variants in TMEM163 cause a hypomyelinating leukodystrophy and uncover a novel role for zinc homeostasis in oligodendrocyte development and myelin formation.

In [40]:
# now we can apply this function to all the articles
articles_hpo = {pmid: nlp_article(article) for pmid, article in articles.items()}

short stature C0013336 [Term('HP:0003510', name='Severe short stature')]
Short stature C0013336 [Term('HP:0003510', name='Severe short stature')]
short stature genes C0013336 [Term('HP:0003510', name='Severe short stature')]
severe C0205082 [Term('HP:0012828', name='Severe')]
progressive C0205329 [Term('HP:0003676', name='Progressive')]
cortical atrophy C0235946 [Term('HP:0002120', name='Cerebral cortical atrophy'), Term('HP:0012444', name='Brain atrophy')]
dystopia canthorum C0423113 [Term('HP:0000506', name='Telecanthus')]
pigmentary changes C1260926 [Term('HP:0001000', name='Abnormality of skin pigmentation')]
hypotonia C0026827 [Term('HP:0001252', name='Hypotonia')]
intellectual disability C3714756 [Term('HP:0001249', name='Intellectual disability')]
craniofacial dysmorphism C0266617 [Term('HP:0000271', name='Abnormality of the face')]
short stature C0013336 [Term('HP:0003510', name='Severe short stature')]
skeletal anomalies C4021790 [Term('HP:0000924', name='Abnormality of the skeletal system')]
short stature C0013336 [Term('HP:0003510', name='Severe short stature')]
Pelizaeus-Merzbacher disease C0205711 [Term('HP:0003269', name='Sudanophilic leukodystrophy')]
congenital nystagmus C0700501 [Term('HP:0006934', name='Congenital nystagmus')]
hypotonia C0026827 [Term('HP:0001252', name='Hypotonia')]
diffuse C0205219 [Term('HP:0020034', name='Diffuse')]
lymphedema C0024236 [Term('HP:0001004', name='Lymphedema')]
distichiasis C0423848 [Term('HP:0008496', name='Multiple rows of eyelashes'), Term('HP:0009743', name='Distichiasis')]
intellectual disability C3714756 [Term('HP:0001249', name='Intellectual disability')]
autism C0004352 [Term('HP:0000717', name='Autism')]
Seizures C0036572 [Term('HP:0001250', name='Seizure')]
spasticity C0026838 [Term('HP:0001257', name='Spasticity')]
intellectual disability C3714756 [Term('HP:0001249', name='Intellectual disability')]
maculopathy C0024437 [Term('HP:0000608', name='Macular degeneration')]
distal amyotrophy C1848736 [Term('HP:0003693', name='Distal amyotrophy')]
dysarthria C0013362 [Term('HP:0001260', name='Dysarthria')]
intellectual deterioration C0234985 [Term('HP:0001268', name='Mental deterioration')]
autosomal dominant HSP C0443147 [Term('HP:0000006', name='Autosomal dominant inheritance')]
Pelizaeus-Merzbacher disease C0205711 [Term('HP:0003269', name='Sudanophilic leukodystrophy')]
PMD C0205711 [Term('HP:0003269', name='Sudanophilic leukodystrophy')]
localized C0392752 [Term('HP:0012838', name='Localized')]
enteropathy C0021831 [Term('HP:0002242', name='Abnormal intestine morphology')]
severe C0205082 [Term('HP:0012828', name='Severe')]
axonal neuropathy C0270921 [Term('HP:0003477', name='Peripheral axonal neuropathy')]
moderate C0205081 [Term('HP:0012826', name='Moderate')]
premature male C0151526 [Term('HP:0001622', name='Premature birth')]
hydrops C0013604 [Term('HP:0000969', name='Edema')]
hepatomegaly C0019209 [Term('HP:0002240', name='Hepatomegaly')]
isolated deficiency C0013338 [Term('HP:0000839', name='Pituitary dwarfism')]
hydrops fetalis C0020305 [Term('HP:0001789', name='Hydrops fetalis')]
Hyperekplexia C0234166 [Term('HP:0002267', name='Exaggerated startle response')]
Sideroblastic anemia C0002896 [Term('HP:0001924', name='Sideroblastic anemia'), Term('HP:0004864', name='Elevated bone marrow ring sideroblast count')]
ineffective erythropoiesis C0392708 [Term('HP:0010972', name='Anemia of inadequate production')]
refractory anemia C0002893 [Term('HP:0005505', name='Refractory anemia')]
Intellectual Disability C3714756 [Term('HP:0001249', name='Intellectual disability')]
intellectual disability C3714756 [Term('HP:0001249', name='Intellectual disability')]
ID C3714756 [Term('HP:0001249', name='Intellectual disability')]
facial dysmorphology C0266617 [Term('HP:0000271', name='Abnormality of the face')]
generalized hypotonia C1858120 [Term('HP:0001290', name='Generalized hypotonia')]
severe C0205082 [Term('HP:0012828', name='Severe')]
spondyloepimetaphyseal dysplasia C0432211 [Term('HP:0002651', name='Spondyloepimetaphyseal dysplasia')]
Cataracts C0086543 [Term('HP:0000518', name='Cataract')]
intellectual disability C3714756 [Term('HP:0001249', name='Intellectual disability')]
cataracts C0086543 [Term('HP:0000518', name='Cataract')]
severe C0205082 [Term('HP:0012828', name='Severe')]
cerebral atrophy C0235946 [Term('HP:0002120', name='Cerebral cortical atrophy'), Term('HP:0012444', name='Brain atrophy')]
LIS1 C0431375 [Term('HP:0006818', name='4-layered lissencephaly')]
bilateral C0238767 [Term('HP:0012832', name='Bilateral')]
severe C0205082 [Term('HP:0012828', name='Severe')]
lissencephaly C0266463 [Term('HP:0001339', name='Lissencephaly')]
PCH-SBH C0266483 [Term('HP:0001302', name='Pachygyria')]
polyhydramnios C0020224 [Term('HP:0001561', name='Polyhydramnios')]
megalencephaly C0221355 [Term('HP:0001355', name='Megalencephaly')]
Polyhydramnios C0020224 [Term('HP:0001561', name='Polyhydramnios')]
severe C0205082 [Term('HP:0012828', name='Severe')]
macrocephaly C0221355 [Term('HP:0001355', name='Megalencephaly')]
craniofacial dysmorphism C0266617 [Term('HP:0000271', name='Abnormality of the face')]
hypotonia C0026827 [Term('HP:0001252', name='Hypotonia')]
low muscle C0026827 [Term('HP:0001252', name='Hypotonia')]
dysmorphic facial features C0424503 [Term('HP:0001999', name='Abnormal facial shape')]
long face C1836047 [Term('HP:0000276', name='Long face')]
wide mouth C0024433 [Term('HP:0000154', name='Wide mouth')]
lymphedema C0024236 [Term('HP:0001004', name='Lymphedema')]
anophthalmia C0003119 [Term('HP:0000528', name='Anophthalmia')]
pituitary C0032002 [Term('HP:0012503', name='Abnormal pituitary gland morphology')]
severe C0205082 [Term('HP:0012828', name='Severe')]
CPHD C0242343 [Term('HP:0000871', name='Panhypopituitarism')]
Leukemia C0023418 [Term('HP:0001909', name='Leukemia')]
obesity C0028754 [Term('HP:0001513', name='Obesity')]
retinitis pigmentosa C0035334 [Term('HP:0000510', name='Rod-cone dystrophy'), Term('HP:0000580', name='Pigmentary retinopathy')]
polydactyly C0152427 [Term('HP:0010442', name='Polydactyly')]
hypogonadism C0020619 [Term('HP:0000135', name='Hypogonadism')]
diabetes mellitus C0011849 [Term('HP:0000819', name='Diabetes mellitus')]
cardiac anomalies C0018798 [Term('HP:0001627', name='Abnormal heart morphology')]
autism C0004352 [Term('HP:0000717', name='Autism')]
schizophrenia C0036341 [Term('HP:0100753', name='Schizophrenia')]
severe C0205082 [Term('HP:0012828', name='Severe')]
Joubert syndrome C0431399 [Term('HP:0002335', name='Agenesis of cerebellar vermis')]
JBTS C0431399 [Term('HP:0002335', name='Agenesis of cerebellar vermis')]
Episodic dystonia C0393588 [Term('HP:0002268', name='Paroxysmal dystonia')]
hypotonia C0026827 [Term('HP:0001252', name='Hypotonia')]
ataxia C0004134 [Term('HP:0010867', name='Dyssynergia')]
Null leukemia C0023418 [Term('HP:0001909', name='Leukemia')]
severe C0205082 [Term('HP:0012828', name='Severe')]
metaphyses C1849039 [Term('HP:0003016', name='Metaphyseal widening')]
autosomal-dominant C0443147 [Term('HP:0000006', name='Autosomal dominant inheritance')]
skeletal anomalies C4021790 [Term('HP:0000924', name='Abnormality of the skeletal system')]
short stature C0013336 [Term('HP:0003510', name='Severe short stature')]
macrocephaly C0221355 [Term('HP:0001355', name='Megalencephaly')]
intellectual disability C3714756 [Term('HP:0001249', name='Intellectual disability')]
muscle cramps C0026821 [Term('HP:0003394', name='Muscle spasm')]
intellectual disability C3714756 [Term('HP:0001249', name='Intellectual disability')]
intellectual disability C3714756 [Term('HP:0001249', name='Intellectual disability')]
Agammaglobulinemia C0001768 [Term('HP:0004432', name='Agammaglobulinemia')]
colitis C0009319 [Term('HP:0002583', name='Colitis')]
recessive intellectual disability C3714756 [Term('HP:0001249', name='Intellectual disability')]
Cause Intellectual Disability C3714756 [Term('HP:0001249', name='Intellectual disability')]
Speech Delay C0241210 [Term('HP:0000750', name='Delayed speech and language development')]
Short Stature C0013336 [Term('HP:0003510', name='Severe short stature')]
oculomotor disorder C0028866 [Term('HP:0012246', name='Oculomotor nerve palsy')]
bilateral C0238767 [Term('HP:0012832', name='Bilateral')]
X-linked ICN C0241764 [Term('HP:0001417', name='X-linked inheritance')]
XLICN C0241764 [Term('HP:0001417', name='X-linked inheritance')]
FERM C0238394 [Term('HP:0010458', name='Female pseudohermaphroditism')]
visual field loss C3887875 [Term('HP:0001123', name='Visual field defect')]
localized C0392752 [Term('HP:0012838', name='Localized')]
rigid spine C1858025 [Term('HP:0003306', name='Spinal rigidity')]
severe C0205082 [Term('HP:0012828', name='Severe')]
X-linked dominant condition C1847879 [Term('HP:0001423', name='X-linked dominant inheritance')]
facial dysmorphic C0266617 [Term('HP:0000271', name='Abnormality of the face')]
congenital heart defects C0018798 [Term('HP:0001627', name='Abnormal heart morphology')]
dental anomalies C0262444 [Term('HP:0000164', name='Abnormality of the dentition'), Term('HP:0006482', name='Abnormal dental morphology')]
X-linked recessive pattern C1845977 [Term('HP:0001419', name='X-linked recessive inheritance')]
malformed ears C0857379 [Term('HP:0000377', name='Abnormal pinna morphology')]
urogenital anomalies C0042063 [Term('HP:0000119', name='Abnormality of the genitourinary system')]
fatigued C0015672 [Term('HP:0012378', name='Fatigue')]
Progressive C0205329 [Term('HP:0003676', name='Progressive')]
Dystonia C0013421 [Term('HP:0001332', name='Dystonia')]
moderate-to-severe intellectual disability C0026351 [Term('HP:0002342', name='Moderate intellectual disability')]
hypotonia C0026827 [Term('HP:0001252', name='Hypotonia')]
Hemimegalencephaly C0431391 [Term('HP:0007206', name='Hemimegalencephaly')]
HMG C0431391 [Term('HP:0007206', name='Hemimegalencephaly')]
Mucolipidosis II C0020725 [Term('HP:0003264', name='Deficiency of N-acetylglucosamine-1-phosphotransferase')]
renal cysts C3887499 [Term('HP:0000107', name='Renal cyst')]
diabetes mellitus C0011849 [Term('HP:0000819', name='Diabetes mellitus')]
nephrogenic C1320468 [Term('HP:0100880', name='Nephrogenic rest')]
Hyperuricemia C0740394 [Term('HP:0002149', name='Hyperuricemia')]
renal failure C0035078 [Term('HP:0000083', name='Renal insufficiency')]
spinal muscular atrophy C0026847 [Term('HP:0007269', name='Spinal muscular atrophy')]
recessive form C0441748 [Term('HP:0000007', name='Autosomal recessive inheritance')]
congenital heart defects C0018798 [Term('HP:0001627', name='Abnormal heart morphology')]
Congenital heart defects C0018798 [Term('HP:0001627', name='Abnormal heart morphology')]
CHDs C0018798 [Term('HP:0001627', name='Abnormal heart morphology')]
cardiac septal C0018816 [Term('HP:0001671', name='Abnormal cardiac septum morphology')]
Chronic destructive-airway disease C0024117 [Term('HP:0006510', name='Chronic pulmonary obstruction')]
male infertility C0021364 [Term('HP:0003251', name='Male infertility')]
situs inversus C0037221 [Term('HP:0003363', name='Abdominal situs inversus')]
situs ambiguous C0266642 [Term('HP:0001696', name='Situs inversus totalis'), Term('HP:0030853', name='Heterotaxy')]
severe C0205082 [Term('HP:0012828', name='Severe')]
peripheral neuropathy C0031117 [Term('HP:0000759', name='Abnormal peripheral nervous system morphology')]
Peripheral neuropathy C0031117 [Term('HP:0000759', name='Abnormal peripheral nervous system morphology')]
sensorimotor neuropathy C1112256 [Term('HP:0007141', name='Sensorimotor neuropathy')]
hyperphenylalaninemia C0751435 [Term('HP:0004923', name='Hyperphenylalaninemia')]
Hyperphenylalaninemia C0751435 [Term('HP:0004923', name='Hyperphenylalaninemia')]
HPA C0751435 [Term('HP:0004923', name='Hyperphenylalaninemia')]
episodic ataxia C1720189 [Term('HP:0002131', name='Episodic ataxia')]
Episodic ataxias C1720189 [Term('HP:0002131', name='Episodic ataxia')]
EAs C1720189 [Term('HP:0002131', name='Episodic ataxia')]
ataxia C0004134 [Term('HP:0010867', name='Dyssynergia')]
neuropathy C0442874 [Term('HP:0009830', name='Peripheral neuropathy')]
ichthyosis C0020757 [Term('HP:0008064', name='Ichthyosis')]
dermatological manifestations C4025812 [Term('HP:0001005', name='Dermatological manifestations of systemic disorders')]
localized C0392752 [Term('HP:0012838', name='Localized')]
mislocation C0012691 [Term('HP:0001373', name='Joint dislocation')]
intellectual disability C3714756 [Term('HP:0001249', name='Intellectual disability')]
seizures C0036572 [Term('HP:0001250', name='Seizure')]
severe C0205082 [Term('HP:0012828', name='Severe')]
intellectual disability C3714756 [Term('HP:0001249', name='Intellectual disability')]
dysmorphic facial features C0424503 [Term('HP:0001999', name='Abnormal facial shape')]
late onset forms C4025592 [Term('HP:0003584', name='Late onset')]
pituitary C0032002 [Term('HP:0012503', name='Abnormal pituitary gland morphology')]
intellectual disability C3714756 [Term('HP:0001249', name='Intellectual disability')]
malignancies C0006826 [Term('HP:0002664', name='Neoplasm')]
hyperkalemic C0238357 [Term('HP:0007215', name='Periodic hyperkalemic paralysis')]
HYPP C0238357 [Term('HP:0007215', name='Periodic hyperkalemic paralysis')]
coloboma C0009363 [Term('HP:0000589', name='Coloboma')]
Ocular coloboma C0009363 [Term('HP:0000589', name='Coloboma')]
eye malformation C0015393 [Term('HP:0000478', name='Abnormality of the eye')]
Coloboma C0009363 [Term('HP:0000589', name='Coloboma')]
freckling C0016689 [Term('HP:0001480', name='Freckling')]
lacrimal duct stenosis C0238300 [Term('HP:0007678', name='Lacrimal duct stenosis')]
oligodontia C0020608 [Term('HP:0000668', name='Hypodontia')]
dystrophic nails C0221260 [Term('HP:0008404', name='Nail dystrophy')]
bilateral athelia C0238767 [Term('HP:0012832', name='Bilateral')]
ulnar ray hypoplasia C1860614 [Term('HP:0003022', name='Hypoplasia of the ulna')]
bilateral C0238767 [Term('HP:0012832', name='Bilateral')]
brachydactyly C0221357 [Term('HP:0001156', name='Brachydactyly')]
imperforate anus C0003466 [Term('HP:0002023', name='Anal atresia')]
Cause Joubert Syndrome C0431399 [Term('HP:0002335', name='Agenesis of cerebellar vermis')]
Joubert syndrome C0431399 [Term('HP:0002335', name='Agenesis of cerebellar vermis')]
JS C0431399 [Term('HP:0002335', name='Agenesis of cerebellar vermis')]
hypotonia C0026827 [Term('HP:0001252', name='Hypotonia')]
ataxia C0004134 [Term('HP:0010867', name='Dyssynergia')]
molar tooth sign C1865060 [Term('HP:0002419', name='Molar tooth sign on MRI')]
coloboma C0009363 [Term('HP:0000589', name='Coloboma')]
polydactyly C0152427 [Term('HP:0010442', name='Polydactyly')]
encephalocele C0014065 [Term('HP:0002084', name='Encephalocele'), Term('HP:0011815', name='Cephalocele')]
progressive C0205329 [Term('HP:0003676', name='Progressive')]
retinal dystrophy C0854723 [Term('HP:0000556', name='Retinal dystrophy')]
liver fibrosis C0239946 [Term('HP:0001395', name='Hepatic fibrosis')]
localize C0392752 [Term('HP:0012838', name='Localized')]
cardiac rhabdomyomas C1332852 [Term('HP:0009729', name='Cardiac rhabdomyoma')]
telecanthus C0423113 [Term('HP:0000506', name='Telecanthus')]
autosomal dominant C0443147 [Term('HP:0000006', name='Autosomal dominant inheritance')]
short stature C0013336 [Term('HP:0003510', name='Severe short stature')]
limb shortening C0239399 [Term('HP:0009815', name='Aplasia/hypoplasia of the extremities'), Term('HP:0009826', name='Limb undergrowth')]
severe C0205082 [Term('HP:0012828', name='Severe')]
recessive form C0441748 [Term('HP:0000007', name='Autosomal recessive inheritance')]
Pelizaeus-Merzbacher disease C0205711 [Term('HP:0003269', name='Sudanophilic leukodystrophy')]
PMD C0205711 [Term('HP:0003269', name='Sudanophilic leukodystrophy')]
X-linked recessive disorder C1845977 [Term('HP:0001419', name='X-linked recessive inheritance')]
severe C0205082 [Term('HP:0012828', name='Severe')]
neurodevelopmental delay C4022738 [Term('HP:0012758', name='Neurodevelopmental delay')]
corneal opacity C0010038 [Term('HP:0007957', name='Corneal opacity')]
glaucoma C0017601 [Term('HP:0000501', name='Glaucoma')]
severe C0205082 [Term('HP:0012828', name='Severe')]
Severe C0205082 [Term('HP:0012828', name='Severe')]
hyperlysinemia C0268553 [Term('HP:0002161', name='Hyperlysinemia')]
severe C0205082 [Term('HP:0012828', name='Severe')]
encephalopathy C0085584 [Term('HP:0001298', name='Encephalopathy')]
Hypertrichosis C0020555 [Term('HP:0000998', name='Hypertrichosis')]
Mitochondrial Dysfunction C4021734 [Term('HP:0003287', name='Abnormality of mitochondrial metabolism')]
coronal craniosynostosis C1856266 [Term('HP:0004440', name='Coronal craniosynostosis')]
severe C0205082 [Term('HP:0012828', name='Severe')]
facial hypertrichosis C1851400 [Term('HP:0002219', name='Facial hypertrichosis')]
short stature C0013336 [Term('HP:0003510', name='Severe short stature')]
Variable lipoatrophy C0023787 [Term('HP:0009125', name='Lipodystrophy')]
cutis laxa C0010495 [Term('HP:0000973', name='Cutis laxa')]
nonprogressive C3839460 [Term('HP:0003680', name='Nonprogressive')]
hypotonia C0026827 [Term('HP:0001252', name='Hypotonia')]
ataxia C0004134 [Term('HP:0010867', name='Dyssynergia')]
intellectual disability C3714756 [Term('HP:0001249', name='Intellectual disability')]
somatic mosaicism C1866227 [Term('HP:0001442', name='Typified by somatic mosaicism')]
neurodegenerative disorder C0524851 [Term('HP:0002180', name='Neurodegeneration')]
Diabetes Insipidus C0011848 [Term('HP:0000873', name='Diabetes insipidus')]
Diabetes Mellitus C0011849 [Term('HP:0000819', name='Diabetes mellitus')]
Optic Atrophy C0029124 [Term('HP:0000648', name='Optic atrophy')]
rickets C0035579 [Term('HP:0002748', name='Rickets')]
osteomalacia C0029442 [Term('HP:0002749', name='Osteomalacia')]
congenital hearing impairment C4021537 [Term('HP:0008591', name='Congenital conductive hearing impairment')]
autosomal dominant diseases C0443147 [Term('HP:0000006', name='Autosomal dominant inheritance')]
sensorineural hearing impairment C0018784 [Term('HP:0000407', name='Sensorineural hearing impairment')]
LFSNHI C3810445 [Term('HP:0008573', name='Low-frequency sensorineural hearing impairment')]
diabetes mellitus C0011849 [Term('HP:0000819', name='Diabetes mellitus')]
optic atrophy C0029124 [Term('HP:0000648', name='Optic atrophy')]
Pulmonary Hypoplasia C0265783 [Term('HP:0002089', name='Pulmonary hypoplasia')]
progressive C0205329 [Term('HP:0003676', name='Progressive')]
hyperactivity C0424295 [Term('HP:0000752', name='Hyperactivity')]
severe C0205082 [Term('HP:0012828', name='Severe')]
neurodegenerative disorder C0524851 [Term('HP:0002180', name='Neurodegeneration')]
retinal dystrophy C0854723 [Term('HP:0000556', name='Retinal dystrophy')]
obesity C0028754 [Term('HP:0001513', name='Obesity')]
hypogenitalism C1855333 [Term('HP:0003241', name='External genital hypoplasia')]
renal anomalies C0266292 [Term('HP:0000077', name='Abnormality of the kidney'), Term('HP:0012210', name='Abnormal renal morphology')]
congenital glaucoma C0020302 [Term('HP:0001087', name='Developmental glaucoma')]
PCG C0020302 [Term('HP:0001087', name='Developmental glaucoma')]
Optic nerve coloboma C0155299 [Term('HP:0000588', name='Optic disc coloboma')]
Optic nerve colobomas C0155299 [Term('HP:0000588', name='Optic disc coloboma')]
midline encephaloceles C0014065 [Term('HP:0002084', name='Encephalocele'), Term('HP:0011815', name='Cephalocele')]
optic nerve colobomas C0155299 [Term('HP:0000588', name='Optic disc coloboma')]
optic nerve coloboma C0155299 [Term('HP:0000588', name='Optic disc coloboma')]
diabetes ketoacidosis C0011880 [Term('HP:0001953', name='Diabetic ketoacidosis')]
severe C0205082 [Term('HP:0012828', name='Severe')]
hyperglycemia C0020456 [Term('HP:0003074', name='Hyperglycemia')]
progressive C0205329 [Term('HP:0003676', name='Progressive')]

In [41]:
# let's look at the results from the first 10 articles
list(articles_hpo.items())[:10]

# what percentage of articles have HPO terms
articles_with_hpo = [k for k,v in articles_hpo.items() if v]
print(f'Percentage of articles with HPO terms: {len(articles_with_hpo)/len(articles)*100:.2f}%')

Percentage of articles with HPO terms: 51.77%

In [42]:
# find the unique HPO terms found in the articles
unique_hpo_terms = list(set([term for terms in articles_hpo.values() for term in terms]))

# create a dataframe to store the data
df = pd.DataFrame(index=articles.keys(), columns=unique_hpo_terms)

# fill the dataframe
for pmid, terms in articles_hpo.items():
    df.loc[pmid, terms] = 1

# fill the NaN values with 0
df.fillna(0, inplace=True)

# print the first 5 rows
df.head()

,HP:0001847,HP:0003693,HP:0004923,HP:0001087,HP:0001288,HP:0000647,HP:0001955,HP:0004432,HP:0012826,HP:0000171,...,HP:0000508,HP:0000592,HP:0000486,HP:0003811,HP:0003477,HP:0001300,HP:0005505,HP:0001891,HP:0003241,HP:0000970
30809043,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23542699,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35607853,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16752401,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19015483,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [43]:
# count the number of times each term appears and store this in a dataframe with columns
# 'HPO Term Name', 'HPO Term', 'Count' and sort by count
hpo_counts = df.sum().sort_values(ascending=False).reset_index()
hpo_counts.columns = ['HPO Term', 'Count']
hpo_counts['HPO Term Name'] = [hpo[term].name for term in hpo_counts['HPO Term']]

# use PrettyTable to display the data
from prettytable import PrettyTable

table = PrettyTable()
table.field_names = hpo_counts.columns
for row in hpo_counts.itertuples(index=False):
    table.add_row(row)
print(table)

+------------+-------+--------------------------------------------------------+
|  HPO Term  | Count |                     HPO Term Name                      |
+------------+-------+--------------------------------------------------------+
| HP:0012828 |   84  |                         Severe                         |
| HP:0001249 |   54  |                Intellectual disability                 |
| HP:0003676 |   38  |                      Progressive                       |
| HP:0001250 |   29  |                        Seizure                         |
| HP:0003510 |   25  |                  Severe short stature                  |
| HP:0001252 |   23  |                       Hypotonia                        |
| HP:0000007 |   16  |            Autosomal recessive inheritance             |
| HP:0000006 |   15  |             Autosomal dominant inheritance             |
| HP:0000271 |   15  |                Abnormality of the face                 |
| HP:0200134 |   14  |                Epileptic encephalopathy                |
| HP:0010867 |   13  |                      Dyssynergia                       |
| HP:0000648 |   12  |                     Optic atrophy                      |
| HP:0001298 |   11  |                     Encephalopathy                     |
| HP:0012838 |   11  |                       Localized                        |
| HP:0001355 |   11  |                     Megalencephaly                     |
| HP:0001627 |   11  |               Abnormal heart morphology                |
| HP:0003198 |   10  |                        Myopathy                        |
| HP:0002180 |   10  |                   Neurodegeneration                    |
| HP:0012832 |   10  |                       Bilateral                        |
| HP:0001257 |   9   |                       Spasticity                       |
| HP:0000407 |   9   |            Sensorineural hearing impairment            |
| HP:0001417 |   8   |                  X-linked inheritance                  |
| HP:0001419 |   8   |             X-linked recessive inheritance             |
| HP:0000518 |   8   |                        Cataract                        |
| HP:0001987 |   6   |                     Hyperammonemia                     |
| HP:0000717 |   6   |                         Autism                         |
| HP:0012826 |   6   |                        Moderate                        |
| HP:0000819 |   6   |                   Diabetes mellitus                    |
| HP:0000924 |   6   |           Abnormality of the skeletal system           |
| HP:0003269 |   6   |              Sudanophilic leukodystrophy               |
| HP:0002335 |   6   |             Agenesis of cerebellar vermis              |
| HP:0000510 |   6   |                   Rod-cone dystrophy                   |
| HP:0004923 |   5   |                 Hyperphenylalaninemia                  |
| HP:0000506 |   5   |                      Telecanthus                       |
| HP:0001256 |   5   |              Mild intellectual disability              |
| HP:0001943 |   5   |                      Hypoglycemia                      |
| HP:0000238 |   5   |                     Hydrocephalus                      |
| HP:0000528 |   5   |                      Anophthalmia                      |
| HP:0000589 |   5   |                        Coloboma                        |
| HP:0002721 |   5   |                    Immunodeficiency                    |
| HP:0000556 |   5   |                   Retinal dystrophy                    |
| HP:0002912 |   5   |                 Methylmalonic acidemia                 |
| HP:0009830 |   4   |                 Peripheral neuropathy                  |
| HP:0011451 |   4   |                  Primary microcephaly                  |
| HP:0002960 |   4   |                      Autoimmunity                      |
| HP:0003535 |   4   |              3-Methylglutaconic aciduria               |
| HP:0000598 |   4   |                 Abnormality of the ear                 |
| HP:0001087 |   4   |                 Developmental glaucoma                 |
| HP:0012758 |   4   |                Neurodevelopmental delay                |
| HP:0010442 |   4   |                      Polydactyly                       |
| HP:0001159 |   4   |                       Syndactyly                       |
| HP:0000829 |   4   |                   Hypoparathyroidism                   |
| HP:0000077 |   4   |               Abnormality of the kidney                |
| HP:0001639 |   4   |              Hypertrophic cardiomyopathy               |
| HP:0000501 |   4   |                        Glaucoma                        |
| HP:0003593 |   4   |                    Infantile onset                     |
| HP:0002120 |   4   |               Cerebral cortical atrophy                |
| HP:0001513 |   4   |                        Obesity                         |
| HP:0000135 |   4   |                      Hypogonadism                      |
| HP:0002352 |   3   |                  Leukoencephalopathy                   |
| HP:0001156 |   3   |                     Brachydactyly                      |
| HP:0002664 |   3   |                        Neoplasm                        |
| HP:0000759 |   3   |     Abnormal peripheral nervous system morphology      |
| HP:0001999 |   3   |                 Abnormal facial shape                  |
| HP:0001644 |   3   |                 Dilated cardiomyopathy                 |
| HP:0000316 |   3   |                     Hypertelorism                      |
| HP:0000839 |   3   |                   Pituitary dwarfism                   |
| HP:0000347 |   3   |                      Micrognathia                      |
| HP:0002803 |   3   |                 Congenital contracture                 |
| HP:0002719 |   3   |                  Recurrent infections                  |
| HP:0000164 |   3   |              Abnormality of the dentition              |
| HP:0012531 |   3   |                          Pain                          |
| HP:0008288 |   3   |               Nonketotic hyperglycinemia               |
| HP:0002758 |   3   |                     Osteoarthritis                     |
| HP:0001288 |   3   |                    Gait disturbance                    |
| HP:0000618 |   3   |                       Blindness                        |
| HP:0001924 |   3   |                  Sideroblastic anemia                  |
| HP:0003477 |   3   |              Peripheral axonal neuropathy              |
| HP:0003756 |   3   |                   Skeletal myopathy                    |
| HP:0000508 |   3   |                         Ptosis                         |
| HP:0000478 |   3   |                 Abnormality of the eye                 |
| HP:0012839 |   3   |                         Distal                         |
| HP:0002415 |   3   |                     Leukodystrophy                     |
| HP:0002651 |   3   |            Spondyloepimetaphyseal dysplasia            |
| HP:0000028 |   3   |                     Cryptorchidism                     |
| HP:0011968 |   3   |                  Feeding difficulties                  |
| HP:0012837 |   3   |                      Generalized                       |
| HP:0000119 |   3   |        Abnormality of the genitourinary system         |
| HP:0003470 |   3   |                       Paralysis                        |
| HP:0003828 |   3   |                 Variable expressivity                  |
| HP:0001638 |   3   |                     Cardiomyopathy                     |
| HP:0001332 |   3   |                        Dystonia                        |
| HP:0002804 |   3   |           Arthrogryposis multiplex congenita           |
| HP:0000707 |   3   |           Abnormality of the nervous system            |
| HP:0001251 |   3   |                         Ataxia                         |
| HP:0000729 |   3   |                   Autistic behavior                    |
| HP:0000842 |   3   |                    Hyperinsulinemia                    |
| HP:0002000 |   2   |                    Short columella                     |
| HP:0004940 |   2   |           Generalized arterial calcification           |
| HP:0003306 |   2   |                    Spinal rigidity                     |
| HP:0001360 |   2   |                   Holoprosencephaly                    |
| HP:0012072 |   2   |                        Aciduria                        |
| HP:0008258 |   2   |             Congenital adrenal hyperplasia             |
| HP:0003560 |   2   |                   Muscular dystrophy                   |
| HP:0001339 |   2   |                     Lissencephaly                      |
| HP:0000970 |   2   |                       Anhidrosis                       |
| HP:0002725 |   2   |              Systemic lupus erythematosus              |
| HP:0010458 |   2   |              Female pseudohermaphroditism              |
| HP:0000154 |   2   |                       Wide mouth                       |
| HP:0000973 |   2   |                       Cutis laxa                       |
| HP:0001985 |   2   |                Hypoketotic hypoglycemia                |
| HP:0000873 |   2   |                   Diabetes insipidus                   |
| HP:0001909 |   2   |                        Leukemia                        |
| HP:0001622 |   2   |                    Premature birth                     |
| HP:0006510 |   2   |             Chronic pulmonary obstruction              |
| HP:0000608 |   2   |                  Macular degeneration                  |
| HP:0007354 |   2   |             Amyotrophic lateral sclerosis              |
| HP:0012503 |   2   |          Abnormal pituitary gland morphology           |
| HP:0007215 |   2   |            Periodic hyperkalemic paralysis             |
| HP:0000852 |   2   |                Pseudohypoparathyroidism                |
| HP:0001268 |   2   |                  Mental deterioration                  |
| HP:0002240 |   2   |                      Hepatomegaly                      |
| HP:0004942 |   2   |                    Aortic aneurysm                     |
| HP:0000588 |   2   |                  Optic disc coloboma                   |
| HP:0001166 |   2   |                     Arachnodactyly                     |
| HP:0000742 |   2   |                    Self-mutilation                     |
| HP:0000821 |   2   |                     Hypothyroidism                     |
| HP:0003693 |   2   |                   Distal amyotrophy                    |
| HP:0008404 |   2   |                     Nail dystrophy                     |
| HP:0010579 |   2   |                 Cone-shaped epiphysis                  |
| HP:0002014 |   2   |                        Diarrhea                        |
| HP:0001945 |   2   |                         Fever                          |
| HP:0000204 |   2   |                    Cleft upper lip                     |
| HP:0007359 |   2   |                  Focal-onset seizure                   |
| HP:0001878 |   2   |                    Hemolytic anemia                    |
| HP:0002655 |   2   |              Spondyloepiphyseal dysplasia              |
| HP:0002161 |   2   |                     Hyperlysinemia                     |
| HP:0000202 |   2   |                    Orofacial cleft                     |
| HP:0000639 |   2   |                       Nystagmus                        |
| HP:0011304 |   2   |                      Broad thumb                       |
| HP:0002659 |   2   |         Increased susceptibility to fractures          |
| HP:0002667 |   2   |                     Nephroblastoma                     |
| HP:0001022 |   2   |                        Albinism                        |
| HP:0002156 |   2   |                     Homocystinuria                     |
| HP:0007269 |   2   |                Spinal muscular atrophy                 |
| HP:0011100 |   2   |                   Intestinal atresia                   |
| HP:0000457 |   2   |                 Depressed nasal ridge                  |
| HP:0000943 |   2   |                  Dysostosis multiplex                  |
| HP:0004482 |   2   |                 Relative macrocephaly                  |
| HP:0006934 |   2   |                  Congenital nystagmus                  |
| HP:0000558 |   2   |                     Rieger anomaly                     |
| HP:0100257 |   2   |                      Ectrodactyly                      |
| HP:0009059 |   2   |          Congenital generalized lipodystrophy          |
| HP:0000463 |   2   |                    Anteverted nares                    |
| HP:0012450 |   2   |                  Chronic constipation                  |
| HP:0000110 |   2   |                    Renal dysplasia                     |
| HP:0001302 |   2   |                       Pachygyria                       |
| HP:0001071 |   2   |            Angiokeratoma corporis diffusum             |
| HP:0001010 |   2   |              Hypopigmentation of the skin              |
| HP:0002023 |   2   |                      Anal atresia                      |
| HP:0002267 |   2   |              Exaggerated startle response              |
| HP:0000090 |   2   |                    Nephronophthisis                    |
| HP:0002084 |   2   |                     Encephalocele                      |
| HP:0002242 |   2   |             Abnormal intestine morphology              |
| HP:0000083 |   2   |                  Renal insufficiency                   |
| HP:0001258 |   2   |                   Spastic paraplegia                   |
| HP:0010739 |   2   |                    Osteopoikilosis                     |
| HP:0002131 |   2   |                    Episodic ataxia                     |
| HP:0000343 |   2   |                     Long philtrum                      |
| HP:0012622 |   2   |                 Chronic kidney disease                 |
| HP:0002654 |   2   |             Multiple epiphyseal dysplasia              |
| HP:0002015 |   2   |                       Dysphagia                        |
| HP:0000763 |   2   |                   Sensory neuropathy                   |
| HP:0002657 |   2   |             Spondylometaphyseal dysplasia              |
| HP:0001631 |   2   |                  Atrial septal defect                  |
| HP:0003394 |   2   |                      Muscle spasm                      |
| HP:0000752 |   2   |                     Hyperactivity                      |
| HP:0001155 |   2   |                Abnormality of the hand                 |
| HP:0001337 |   2   |                         Tremor                         |
| HP:0002762 |   2   |                   Multiple exostoses                   |
| HP:0001635 |   2   |                Congestive heart failure                |
| HP:0001004 |   2   |                       Lymphedema                       |
| HP:0002901 |   2   |                      Hypocalcemia                      |
| HP:0001955 |   2   |                   Unexplained fevers                   |
| HP:0001714 |   1   |                Ventricular hypertrophy                 |
| HP:0005505 |   1   |                   Refractory anemia                    |
| HP:0002268 |   1   |                  Paroxysmal dystonia                   |
| HP:0003241 |   1   |              External genital hypoplasia               |
| HP:0004377 |   1   |                 Hematological neoplasm                 |
| HP:0001052 |   1   |                     Nevus flammeus                     |
| HP:0001300 |   1   |                      Parkinsonism                      |
| HP:0000846 |   1   |                 Adrenal insufficiency                  |
| HP:0100255 |   1   |                 Metaphyseal dysplasia                  |
| HP:0100621 |   1   |                      Dysgerminoma                      |
| HP:0002375 |   1   |                      Hypokinesia                       |
| HP:0001998 |   1   |                 Neonatal hypoglycemia                  |
| HP:0002676 |   1   |                    Cloverleaf skull                    |
| HP:0010535 |   1   |                      Sleep apnea                       |
| HP:0008064 |   1   |                       Ichthyosis                       |
| HP:0000273 |   1   |                    Facial grimacing                    |
| HP:0100515 |   1   |                      Pollakisuria                      |
| HP:0002878 |   1   |                  Respiratory failure                   |
| HP:0001891 |   1   |                 Iron deficiency anemia                 |
| HP:0002634 |   1   |                    Arteriosclerosis                    |
| HP:0002362 |   1   |                     Shuffling gait                     |
| HP:0000097 |   1   |           Focal segmental glomerulosclerosis           |
| HP:0200125 |   1   |        Mitochondrial respiratory chain defects         |
| HP:0100716 |   1   |                Self-injurious behavior                 |
| HP:0002470 |   1   |            Nonprogressive cerebellar ataxia            |
| HP:0003074 |   1   |                     Hyperglycemia                      |
| HP:0005684 |   1   |                 Distal arthrogryposis                  |
| HP:0002376 |   1   |                Developmental regression                |
| HP:0002333 |   1   |                  Motor deterioration                   |
| HP:0002121 |   1   |        Generalized non-motor (absence) seizure         |
| HP:0008551 |   1   |                        Microtia                        |
| HP:0008573 |   1   |     Low-frequency sensorineural hearing impairment     |
| HP:0000659 |   1   |                     Peters anomaly                     |
| HP:0000980 |   1   |                         Pallor                         |
| HP:0002419 |   1   |                Molar tooth sign on MRI                 |
| HP:0007418 |   1   |                    Alopecia totalis                    |
| HP:0000308 |   1   |                   Microretrognathia                    |
| HP:0003584 |   1   |                       Late onset                       |
| HP:0003363 |   1   |                Abdominal situs inversus                |
| HP:0002069 |   1   |             Bilateral tonic-clonic seizure             |
| HP:0000411 |   1   |                     Protruding ear                     |
| HP:0011947 |   1   |              Respiratory tract infection               |
| HP:0000823 |   1   |                    Delayed puberty                     |
| HP:0000062 |   1   |                  Ambiguous genitalia                   |
| HP:0001139 |   1   |                     Choroideremia                      |
| HP:0000592 |   1   |                      Blue sclerae                      |
| HP:0000486 |   1   |                       Strabismus                       |
| HP:0003811 |   1   |                     Neonatal death                     |
| HP:0002344 |   1   |          Progressive neurologic deterioration          |
| HP:0100258 |   1   |                  Preaxial polydactyly                  |
| HP:0007676 |   1   |                 Hypoplasia of the iris                 |
| HP:0002247 |   1   |                    Duodenal atresia                    |
| HP:0007141 |   1   |                Sensorimotor neuropathy                 |
| HP:0006443 |   1   |                    Patellar aplasia                    |
| HP:0011297 |   1   |               Abnormal digit morphology                |
| HP:0002514 |   1   |                 Cerebral calcification                 |
| HP:0001685 |   1   |                  Myocardial fibrosis                   |
| HP:0004485 |   1   |                Cessation of head growth                |
| HP:0010301 |   1   |                   Spinal dysraphism                    |
| HP:0100753 |   1   |                     Schizophrenia                      |
| HP:0008718 |   1   |               Unilateral renal dysplasia               |
| HP:0010603 |   1   |           Odontogenic keratocysts of the jaw           |
| HP:0007002 |   1   |                Motor axonal neuropathy                 |

## Why:
- Are there certain genetic conditions that share genotypes
- Usually it is done by differential diagnosis e.g. similar set of diseases, but seperate on phenotype profile differences
- We are only using abstracts, but you can use this on 4,000,000 full text articles in open pubmed
- These will include patient level phenotype descriptions