### Programming for Biomedical Informatics
#### Week 3 - Data Integration & Summary Analysis

Using some of the skills we've developed working with eUtils we're now going to take two different lists of genes that use different identifiers convert them to NCBI Gene IDs and then use these to merge the data together. With the final merged data we will do some calculations and plots.

In [26]:
# Preliminaries
from Bio import Entrez
import urllib.request
import json
import xml.etree.ElementTree as ET
import pandas as pd

# load my API key from the file
with open('../../bio_api_keys/ncbi.txt', 'r') as file:
    api_key = file.read().strip()

with open('../../bio_api_keys//ncbi_email.txt', 'r') as file:
    email = file.read().strip()

Entrez.api_key = api_key
Entrez.email = email

In [28]:
# Step 1 - Load the two lists that we cannot currenly combine

'''The first file contains a list of gene symbols

e.g.
GeneSymbol
ADAM10
ADAM17
APP
NAE1
APBB1
GAPDH
BACE1

The second file contains a list of RefSeq transcripts (mRNA), and their associated GO terms:

 #NC,NG,NP is refseq - rember NM is NMRNA
e.g.
RefSeqID        GOTerm  Description
NM_001320570    GO:0003824      catalytic activity # Makes protein that catalyses a reaction
NM_001320570    GO:0016787      hydrolase activity
NM_001320570    GO:0140096      catalytic activity, acting on a protein
NM_001320570    GO:0043226      organelle
NM_001320570    GO:0005634      nucleus
NM_001320570    GO:0005794      Golgi apparatus

We are going to convert Gene Symbols and Refseq IDs to NCBI Gene IDs, and then combine the two lists into a single table.
'''

# Load the gene symbols as a pandas dataframe
'''### YOUR CODE HERE ###'''
gene_df = pd.read_csv('./GeneSymbols.tsv', sep = '\t')


# Load the RefSeq data as a pandas dataframe
'''### YOUR CODE HERE ###'''
refseq_df = pd.read_csv('./transcript_functions.tsv', sep = '\t')

In [29]:
# view the first few rows of each dataframe
'''### YOUR CODE HERE ###'''
gene_df.head()

  GeneSymbol
0     ADAM10
1     ADAM17
2        APP
3       NAE1
4      APBB1

In [30]:
# view the first few rows of each dataframe
'''### YOUR CODE HERE ###'''
refseq_df.head()

       RefSeqID      GOTerm                              Description
0  NM_001320570  GO:0003824                       catalytic activity
1  NM_001320570  GO:0016787                       hydrolase activity
2  NM_001320570  GO:0140096  catalytic activity, acting on a protein
3  NM_001320570  GO:0043226                                organelle
4  NM_001320570  GO:0005634                                  nucleus

In [31]:
# Making auxiliary get gene id from gene symbol:

def get_gene_id(gene_iter, organism = 'Homo sapians'):
    gene_id_res = {}
    for gene in gene_iter:
        handle = Entrez.esearch(db = 'gene', term= f'{gene}[gene] AND {organism}[Organism]', retmax = 1)
        record = Entrez.read(handle)
        if record['IdList']:
            gene_id_res[gene] = record['IdList'][0]
        else:
            gene_id_res[gene] = None

    return gene_id_res

## Replicate his approach

In [34]:
from math import e
import urllib.parse
from numpy import record
# the base request url for eSearch
url = f"https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"

db = 'gene'

gene_iter = gene_df['GeneSymbol'].tolist()

db_call_string = ' OR '.join([f'{gene}[Gene]' for gene in gene_iter])
db_call_string = f'(human[Organism]) AND ({db_call_string})' #Joining in the query is () AND/OR ()

db_call_string

'(human[Organism]) AND (ADAM10[Gene] OR ADAM17[Gene] OR APP[Gene] OR NAE1[Gene] OR APBB1[Gene] OR GAPDH[Gene] OR BACE1[Gene] OR BACE2[Gene] OR RTN3[Gene] OR RTN4[Gene] OR PSENEN[Gene] OR PSEN1[Gene] OR PSEN2[Gene] OR NCSTN[Gene] OR APH1A[Gene] OR APH1B[Gene] OR IDE[Gene] OR MME[Gene] OR MAPT[Gene] OR ND1[Gene] OR ND2[Gene] OR ND3[Gene] OR ND4[Gene] OR ND4L[Gene] OR ND5[Gene] OR ND6[Gene] OR NDUFV1[Gene] OR NDUFV2[Gene] OR NDUFV3[Gene] OR NDUFA1[Gene] OR NDUFA2[Gene] OR NDUFA3[Gene] OR NDUFA4[Gene] OR NDUFA4L2[Gene] OR NDUFA5[Gene] OR NDUFA6[Gene] OR NDUFA7[Gene] OR NDUFA8[Gene] OR NDUFA9[Gene] OR NDUFA10[Gene] OR NDUFAB1[Gene] OR NDUFA11[Gene] OR NDUFA12[Gene] OR NDUFA13[Gene] OR NDUFB1[Gene] OR NDUFB2[Gene] OR NDUFB3[Gene] OR NDUFB4[Gene] OR NDUFB5[Gene] OR NDUFB6[Gene] OR NDUFB7[Gene] OR NDUFB8[Gene] OR NDUFB9[Gene] OR NDUFB10[Gene] OR NDUFB11[Gene] OR NDUFS1[Gene] OR NDUFS2[Gene] OR NDUFS3[Gene] OR NDUFS4[Gene] OR NDUFS5[Gene] OR NDUFS6[Gene] OR NDUFS7[Gene] OR NDUFS8[Gene] OR NDUFC1[Gene] OR NDUFC2[Gene] OR SDHA[Gene] OR SDHB[Gene] OR SDHC[Gene] OR SDHD[Gene] OR UQCRFS1[Gene] OR CYTB[Gene] OR CYC1[Gene] OR UQCRC1[Gene] OR UQCRC2[Gene] OR UQCRH[Gene] OR UQCRHL[Gene] OR UQCRB[Gene] OR UQCRQ[Gene] OR UQCR10[Gene] OR UQCR11[Gene] OR COX3[Gene] OR COX1[Gene] OR COX2[Gene] OR COX4I2[Gene] OR COX4I1[Gene] OR COX5A[Gene] OR COX5B[Gene] OR COX6A1[Gene] OR COX6A2[Gene] OR COX6B1[Gene] OR COX6B2[Gene] OR COX6C[Gene] OR COX7A1[Gene] OR COX7A2[Gene] OR COX7A2L[Gene] OR COX7B[Gene] OR COX7B2[Gene] OR COX7C[Gene] OR COX8C[Gene] OR COX8A[Gene] OR ATP5F1A[Gene] OR ATP5F1B[Gene] OR ATP5F1C[Gene] OR ATP5F1D[Gene] OR ATP5F1E[Gene] OR ATP6[Gene] OR ATP5PB[Gene] OR ATP5MC1[Gene] OR ATP5MC2[Gene] OR ATP5MC3[Gene] OR ATP5PD[Gene] OR ATP5PO[Gene] OR ATP5PF[Gene] OR ATP8[Gene] OR HSD17B10[Gene] OR PPID[Gene] OR VDAC1[Gene] OR VDAC2[Gene] OR VDAC3[Gene] OR SLC25A4[Gene] OR SLC25A5[Gene] OR SLC25A6[Gene] OR SLC25A31[Gene] OR PPIF[Gene] OR LPL[Gene] OR APOE[Gene] OR LRP1[Gene] OR FAS[Gene] OR TNFRSF1A[Gene] OR FADD[Gene] OR CASP8[Gene] OR BID[Gene] OR CALML3[Gene] OR CALM2[Gene] OR CALM3[Gene] OR CALM1[Gene] OR CALML6[Gene] OR CALML5[Gene] OR CALML4[Gene] OR PPP3CA[Gene] OR PPP3CB[Gene] OR PPP3CC[Gene] OR PPP3R1[Gene] OR PPP3R2[Gene] OR BAD[Gene] OR CYCS[Gene] OR APAF1[Gene] OR CASP9[Gene] OR CASP3[Gene] OR CHRM1[Gene] OR CHRM3[Gene] OR CHRM5[Gene] OR GRM5[Gene] OR GNAQ[Gene] OR PLCB1[Gene] OR PLCB2[Gene] OR PLCB3[Gene] OR PLCB4[Gene] OR GRIN1[Gene] OR GRIN2A[Gene] OR GRIN2B[Gene] OR GRIN2C[Gene] OR GRIN2D[Gene] OR CACNA1C[Gene] OR CACNA1D[Gene] OR CACNA1F[Gene] OR CACNA1S[Gene] OR CHRNA7[Gene] OR CHRFAM7A[Gene] OR MCU[Gene] OR MAPK1[Gene] OR MAPK3[Gene] OR RYR3[Gene] OR ITPR1[Gene] OR ITPR2[Gene] OR ITPR3[Gene] OR ATP2A1[Gene] OR ATP2A3[Gene] OR ATP2A2[Gene] OR ATF6[Gene] OR XBP1[Gene] OR DDIT3[Gene] OR ERN1[Gene] OR EIF2AK3[Gene] OR TRAF2[Gene] OR MAP3K5[Gene] OR MAP2K7[Gene] OR MAPK8[Gene] OR MAPK10[Gene] OR MAPK9[Gene] OR EIF2S1[Gene] OR ATF4[Gene] OR PSMA6[Gene] OR PSMA2[Gene] OR PSMA4[Gene] OR PSMA7[Gene] OR PSMA8[Gene] OR PSMA5[Gene] OR PSMA1[Gene] OR PSMA3[Gene] OR PSMB6[Gene] OR PSMB7[Gene] OR PSMB3[Gene] OR PSMB2[Gene] OR PSMB5[Gene] OR PSMB1[Gene] OR PSMB4[Gene] OR PSMC2[Gene] OR PSMC1[Gene] OR PSMC4[Gene] OR PSMC6[Gene] OR PSMC3[Gene] OR PSMC5[Gene] OR PSMD2[Gene] OR PSMD1[Gene] OR PSMD3[Gene] OR PSMD9[Gene] OR PSMD12[Gene] OR PSMD11[Gene] OR PSMD6[Gene] OR PSMD7[Gene] OR PSMD13[Gene] OR PSMD4[Gene] OR PSMD14[Gene] OR PSMD8[Gene] OR ADRM1[Gene] OR SEM1[Gene] OR CASP12[Gene] OR NOS1[Gene] OR CAPN1[Gene] OR CAPN2[Gene] OR CDK5R1[Gene] OR SLC39A2[Gene] OR SLC39A3[Gene] OR SLC39A1[Gene] OR SLC39A4[Gene] OR SLC39A5[Gene] OR SLC39A6[Gene] OR SLC39A7[Gene] OR SLC39A8[Gene] OR SLC39A9[Gene] OR SLC39A10[Gene] OR SLC39A11[Gene] OR SLC39A12[Gene] OR SLC39A13[Gene] OR SLC39A14[Gene] OR SLC11A2[Gene] OR CDK5[Gene] OR GSK3B[Gene] OR CASP7[Gene] OR DKK1[Gene] OR DKK2[Gene] OR DKK4[Gene] OR WNT1[Gene] OR WNT2[Gene] OR WNT2B[Gene] OR WNT3[Gene] OR WNT3A[Gene] OR WNT4[Gene] OR WNT5A[Gene] OR WNT5B[Gene] OR WNT6[Gene] OR WNT7A[Gene] OR WNT7B[Gene] OR WNT8A[Gene] OR WNT8B[Gene] OR WNT9A[Gene] OR WNT9B[Gene] OR WNT10B[Gene] OR WNT10A[Gene] OR WNT11[Gene] OR WNT16[Gene] OR FZD1[Gene] OR FZD7[Gene] OR FZD2[Gene] OR FZD3[Gene] OR FZD4[Gene] OR FZD5[Gene] OR FZD8[Gene] OR FZD6[Gene] OR FZD10[Gene] OR FZD9[Gene] OR LRP5[Gene] OR LRP6[Gene] OR CSNK1E[Gene] OR DVL3[Gene] OR DVL2[Gene] OR DVL1[Gene] OR FRAT1[Gene] OR FRAT2[Gene] OR CSNK2A1[Gene] OR CSNK2A2[Gene] OR CSNK2A3[Gene] OR CSNK2B[Gene] OR AXIN1[Gene] OR AXIN2[Gene] OR APC[Gene] OR APC2[Gene] OR CTNNB1[Gene] OR CSNK1A1L[Gene] OR CSNK1A1[Gene] OR KIF5A[Gene] OR KIF5B[Gene] OR KIF5C[Gene] OR KLC3[Gene] OR KLC1[Gene] OR KLC2[Gene] OR KLC4[Gene] OR TUBA1B[Gene] OR TUBA4A[Gene] OR TUBA3C[Gene] OR TUBA1A[Gene] OR TUBA1C[Gene] OR TUBA8[Gene] OR TUBA3E[Gene] OR TUBA3D[Gene] OR TUBAL3[Gene] OR TUBB6[Gene] OR TUBB[Gene] OR TUBB1[Gene] OR TUBB2A[Gene] OR TUBB3[Gene] OR TUBB4A[Gene] OR TUBB8[Gene] OR TUBB2B[Gene] OR TUBB4B[Gene] OR TUBB8B[Gene] OR AGER[Gene] OR HRAS[Gene] OR KRAS[Gene] OR NRAS[Gene] OR ARAF[Gene] OR BRAF[Gene] OR RAF1[Gene] OR MAP2K1[Gene] OR MAP2K2[Gene] OR NOX1[Gene] OR CYBB[Gene] OR NOX4[Gene] OR RELA[Gene] OR NFKB1[Gene] OR NOS2[Gene] OR PTGS2[Gene] OR TNF[Gene] OR IL6[Gene] OR IL1A[Gene] OR IL1B[Gene] OR CSF1[Gene] OR SNCA[Gene] OR EIF2AK2[Gene] OR CHUK[Gene] OR IKBKB[Gene] OR IKBKG[Gene] OR INS[Gene] OR INSR[Gene] OR IRS1[Gene] OR IRS2[Gene] OR IRS4[Gene] OR PIK3R1[Gene] OR PIK3R2[Gene] OR PIK3R3[Gene] OR PIK3CA[Gene] OR PIK3CD[Gene] OR PIK3CB[Gene] OR AKT1[Gene] OR AKT2[Gene] OR AKT3[Gene] OR MTOR[Gene] OR ULK1[Gene] OR ULK2[Gene] OR ATG101[Gene] OR ATG13[Gene] OR RB1CC1[Gene] OR AMBRA1[Gene] OR BECN1[Gene] OR BECN2[Gene] OR PIK3R4[Gene] OR ATG14[Gene] OR NRBF2[Gene] OR PIK3C3[Gene] OR ATG2A[Gene] OR ATG2B[Gene] OR WIPI2[Gene] OR WIPI1[Gene])'

In [43]:


# Define the parameters for the eSearch request
# This can be nicely done using a dictionary
# Note we include the history feature of eUtils to allow us to make large queries efficiently
import urllib.request


esearch_params = {
    'db': db,
    'term':db_call_string,
    'api_key': api_key,
    'email': email,
    'usehistory': 'y'
}
encoded_data = urllib.parse.urlencode(esearch_params).encode('utf-8')

# the base request url for eSearch
url = f"https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"

# make the request
request = urllib.request.Request(url, data=encoded_data)
response = urllib.request.urlopen(request)

# read into an XML object
esearch_data_XML = ET.fromstring(response.read())

for child in esearch_data_XML:
    print(child)

# Extract WebEnv and QueryKey
# Here we use ElementTree to extract the WebEnv and QueryKey from the XML response
# We will use these to fetch the gene ids in the next step using eSummary
webenv = esearch_data_XML.find('WebEnv').text
query_key = esearch_data_XML.find('QueryKey').text
count = esearch_data_XML.find('Count').text

print('webenv:', webenv, 'query_key:', query_key, 'count:', count)

<Element 'Count' at 0x000002CCF0713100>
<Element 'RetMax' at 0x000002CCF0713330>
<Element 'RetStart' at 0x000002CCF0712E30>
<Element 'QueryKey' at 0x000002CCF0712840>
<Element 'WebEnv' at 0x000002CCF07127A0>
<Element 'IdList' at 0x000002CCF0712D90>
<Element 'TranslationSet' at 0x000002CCF072CEA0>
<Element 'TranslationStack' at 0x000002CCF072CF90>
<Element 'QueryTranslation' at 0x000002CCF082B7E0>
webenv: MCID_68fb96e10073de9fff06eb48 query_key: 1 count: 449

NameError: name 'query_key' is not defined

In [77]:
# use eSearch to convert gene symbols to NCBI Gene IDs (for the first 10 gene symbols)
# remembering to add API key and email
# remembering to use the [Gene] field in the search
# remembering to specify human
# show the progress by printing the gene symbol and gene ID and the number of gene symbols processed so far
# This takes about 3 minutes (NB not the quickest way!)

esearch_params_2 = {
    'db': db,
    'query_key': query_key,
    'WebEnv': webenv,
    'api_key': api_key,
    'email': email
}

# the base request url for eSummary
url = f"https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi"

encoded_data_2 = urllib.parse.urlencode(esearch_params_2).encode('utf-8')

# make the request
request = urllib.request.Request(url, data=encoded_data_2)
response = urllib.request.urlopen(request)

# read into an XML object
esummary_data_XML = ET.fromstring(response.read())

gene_symbols_to_id = {}
for child in esearch_data_XML.findall('DocumentSummarySet/DocumentSummary'):
    print(child.find('Name').text)
    print(child.attrib['uid'])
    gene_symbols_to_id[child.find('Name').text] = child.attrib['uid']

# convert the gene_ids dictionary to a pandas dataframe
gene_ids_df = pd.DataFrame(gene_symbols_to_id.items(), columns=['GeneSymbol', 'GeneID'])

# look at the first few rows
gene_ids_df.head()

# take a look
# import xml.dom.minidom

# xml_str = ET.tostring(esummary_data_XML, encoding='utf-8')
# dom = xml.dom.minidom.parseString(xml_str)
# print(dom.toprettyxml())

APOE
348
TNF
7124
IL6
3569
APP
351
KRAS
3845
BRAF
673
AKT1
207
NFKB1
4790
IL1B
3553
CTNNB1
1499
SNCA
6622
PTGS2
5743
MAPT
4137
MTOR
2475
MAPK1
5594
PIK3CA
5290
RELA
5970
GSK3B
2932
FAS
355
AGER
177
INS
3630
CASP3
836
APC
324
MAPK3
5595
PSEN1
5663
NOS2
4843
IL1A
3552
LPL
4023
CASP8
841
HRAS
3265
MAPK8
5599
INSR
3643
TNFRSF1A
7132
CSNK2A1
1457
BECN1
8678
PIK3R1
5295
NRAS
4893
DKK1
22943
IRS1
3667
RAF1
5894
WNT5A
7474
ADAM17
6868
LRP1
4035
BACE1
23621
PROC
5624
CACNA1C
775
FASN
2194
CALM1
801
IKBKB
3551
EIF2AK2
5610
MME
4311
CYBB
1536
NOX4
50507
NOS1
4842
IKBKG
8517
CHRNA7
1139
GAPDH
2597
MAP2K1
5604
ADAM10
102
CASP9
842
CHUK
1147
GRIN2B
2904
CDK5
1020
TRAF2
7186
XBP1
7494
LRP5
4041
GNAQ
2776
ATF4
468
ERN1
2081
ATP2A2
488
AKT2
208
CSF1
1435
SDHB
6390
VDAC1
7416
FADD
8772
PTGS1
5742
DDIT3
1649
TUBB3
10381
GRIN1
2902
MAP3K5
4217
WNT1
7471
EIF2S1
1965
ULK1
8408
BAD
572
IRS2
8660
GRIN2A
2903
LRP6
4040
PSEN2
5664
EIF2AK3
9451
AXIN1
8312
CSNK2B
1460
NOX1
27035
ITPR1
3708
WNT3A
89780
CAPN1
823
RTN4
57142
BID
637
MMP12
4321
PIK3CD
5293
ATF6
22926
TUBB
203068
AKT3
10000
IDE
3416
APAF1
317
CASP7
840
CHRM3
1131
PIK3CB
5291
MAPK9
5601
SDHD
6392
TUBA1A
7846
CSNK2A2
1459
PSMD4
5710
RNASE3
6037
COX2
6775079
AXIN2
8313
CSNK1A1
1452
MAP2K2
5605
ND1
4535
CYCS
54205
PTGER2
5732
PIK3C3
5289
NCSTN
23385
ATP5F1A
498
CAPN2
824
PSMC5
5705
ATP5F1B
506
PPP3CA
5530
GRM5
2915
KIF5B
3799
SLC11A2
4891
TUBA1B
10376
CSNK1E
1454
CALM3
808
PIK3R2
5296
CHRM1
1128
SDHA
6389
SLC25A4
291
ATP6
4508
HSD17B10
3028
PSMD2
5708
PSMA6
5687
CALM2
805
CACNA1S
779
DVL2
1856
SLC25A5
292
TUBB4A
10382
PLCB1
23236
TUBA4A
7277
ITPR3
3710
PSMA7
5688
TUBB2A
7280
PSMB5
5693
FZD4
8322
CACNA1D
776
VDAC2
7417
DVL1
1855
NDUFA13
51079
MAP2K7
5609
WNT4
54361
PSMD1
5707
PSMC3
5702
TUBB4B
10383
PSMC2
5701
KIF5A
3798
WNT7A
7476
PSMC4
5704
PSMA3
5684
APBB1
322
RB1CC1
9821
SLC39A4
55630
CACNA1F
778
PSMD14
10213
PSMC1
5700
WNT10A
80326
PSMD9
5715
ND4
4538
PSMA1
5682
ADRM1
11047
FZD7
8324
COX2
4513
CDK5R1
8851
SLC25A6
293
PSMD3
5709
DVL3
1857
LCP1
3936
MCU
90550
MAPK10
5602
IRS4
8471
PSMC6
5706
WNT2
7472
PSMA4
5685
PSMA2
5683
ND5
4540
PSMA5
5686
RTN3
10313
ND2
4536
PSMD11
5717
COX1
4512
AMBRA1
55626
SDHC
6391
PSMB1
5689
PSENEN
55851
SLC39A8
64116
TUBA1C
84790
SLC39A14
23516
ATG14
22863
PSMB4
5692
BACE2
25825
PSMD12
5718
KLC1
3831
ARAF
369
PIK3R3
8503
PSMD7
5713
GRIN2D
2906
CHRFAM7A
89832
PSMD6
9861
PPP3R1
5534
ATP2A1
487
COX4I1
1327
ITPR2
3709
TUBB6
84617
GRIN2C
2905
PLCB3
5331
WNT10B
7480
PSMD13
5719
NDUFS1
4719
NDUFS3
4722
FZD5
7855
UQCRC2
7385
PSMB7
5695
TUBB8
347688
PPIF
10105
WNT3
7473
ND3
4537
ND6
4541
PLCB2
5330
ATP5F1C
509
PSMB3
5691
PSMB6
5694
WNT2B
7482
VDAC3
7419
PSMB2
5690
NDUFS4
4724
ATP2A3
489
RYR3
6263
ATG13
9776
SLC39A6
25800
TUBB2B
347733
TANK
10010
WNT11
7481
PSMD8
5714
PPP3CB
5532
ATP5PO
539
FZD6
8323
NDUFV2
4729
UQCRC1
7384
ANAPC2
29882
NDUFS2
4720
TUBB1
81027
PPID
5481
SEM1
7979
WNT16
51384
CYC1
1537
DKK2
27123
APH1A
51107
FZD1
8321
WNT7B
7477
FZD3
7976
CYTB
4519
NDUFV1
4723
WNT5B
81029
SLC39A7
7922
CASP12
100506742
PPP3CC
5533
SLC39A2
29986
ATP5PF
522
UQCRB
7381
NDUFA9
4704
FZD2
2535
COXFA4
4697
CALML5
51806
NDUFA5
4698
PIK3R4
30849
ATP5PB
515
PLCB4
5332
SLC39A1
27173
NAE1
8883
COX5B
1329
ATG2B
55102
ND2
6775094
CALML3
810
COX3
4514
NDUFS7
374291
TUBA3C
7278
NDUFA10
4705
DKK4
27121
APC2
10297
FZD8
8325
FRAT1
10023
ATP5PD
10476
WIPI2
26100
KLC2
64837
ULK2
9706
ATP5F1D
513
COX5A
9377
NDUFS8
4728
TUBA8
51807
IVNS1ABP
10625
UQCRFS1
7386
NDUFA8
4702
KIF5C
3800
WNT6
7475
NDUFB11
54539
FZD10
11211
WNT9B
7484
COX6B1
1340
NDUFB6
4712
NDUFA1
4694
ATG2A
23130
NDUFAB1
4706
COX7A1
1346
WNT9A
7483
COX7A2
1347
SLC39A10
57181
COX4I2
84701
UQCRH
7388
COX6C
1345
NDUFS6
4726
SLC39A9
55334
NRBF2
29982
CHRM5
1133
CLSTN1
22883
NDUFB10
4716
ATP5F1E
514
WIPI1
55062
APH1B
83464
ATP8
4509
COXFA4L2
56901
NDUFB9
4715
NDUFS5
4725
NDUFA2
4695
NDUFC2
4718
COX7A2L
9167
NDUFA12
55967
ATP5MC1
516
NDUFV3
4731
ND1
6775098
NDUFB8
4714
C1D
10438
FZD9
8326
ND6
6775063
COX6A1
1337
KLC4
89953
ATG101
60673
NDUFA6
4700
COX7B
1349
CSNK2A3
283106
ND5
6775066
NDUFB7
4713
SLC25A31
83447
PPP3R2
5535
SLC39A13
91252
UQCRQ
27089
NDUFA7
4701
UQCR10
29796
COX1
6775083
NDUFB4
4710
SLC39A11
201266
KLC3
147700
COX7C
1350
GPRIN1
114787
NDUFB5
4711
PSMA8
143471
COX8A
1351
WNT8B
7479
TUBA3E
112714
CCNI
10983
SLC25A23
79085
SLC39A5
283375
ATP5MC2
517
TUBA3D
113457
SLC39A3
29985
COX6A2
1339
TUBAL3
79861
ND4
6775072
WNT8A
7478
ND4L
4539
NDUFA11
126328
NDUFB3
4709
ATP5MC3
518
FRAT2
23401
NANOS1
340719
MTCO2P12
107075310
ND3
6775076
NANOS2
339345
NDUFA3
4696
NDUFB1
4707
NDUFB2
4708
COX6B2
125965
ATP6
6775074
CSNK1A1L
122011
SLC39A12
221074
CALML6
163688
NDUFC1
4717
UQCR11
10975
COX7B2
170712
ND4L
6775071
DVL1P1
8215
BECN2
441925
CALML4
91860
GAPDHP44
100240709
ATP8
6775077
COX8C
341947
CYTB
6775065
COX3
6775073
UQCRHL
440567
XBP1P1
7495
TUBB8B
260334
COX1
8923218
ND2
8923212
ATP8
8923211
ND5
8923210
ND1
8923209
ND3
8923206
CYTB
8923205
COX2
8923202
ND4L
8923201
ND6
8923198
ND4
8923197
ATP6
8923188
COX3
8923187
SDHCP5
642502
VDAC1P5
10187
COXFA4P1
360165
RNU1-93P
106480180
RNU6-664P
106479861
NDUFB11
446098
SLC39A5
378941
SLC39A4
170683
CASP12
120329
WNT10A
93651
RB1CC1
85312
RTN4
57141
KLC2
8185
PSMD6
5712
NDUFS7
4727
LRP5
4039
KNS1
3830
FRAP2
2476

  GeneSymbol GeneID
0       APOE    348
1        TNF   7124
2        IL6   3569
3        APP    351
4       KRAS   3845

In [82]:
gene_ids_df.sort_values(by = 'GeneSymbol', inplace=True)
gene_ids_df.dropna(inplace=True)

In [84]:
gene_ids_df.head()

    GeneSymbol GeneID
58      ADAM10    102
41      ADAM17   6868
177      ADRM1  11047
19        AGER    177
6         AKT1    207

In [ ]:
# Step 3 - Convert RefSeq IDs to NCBI Gene IDs

# create a dictionary that maps RefSeq IDs to Gene IDs
'''### YOUR CODE HERE ###'''

# use eSearch to convert RefSeq IDs to NCBI Gene IDs (for the first 10 RefSeq IDs)
# remembering to add API key and email
# remembering to use the [Gene] field in the search
# remembering to specify human

# Search for the gene information using the RefSeq transcript ID
'''### YOUR CODE HERE ###'''

# for the first unique 10 values in the refseq dataframe, get the gene ID
# show the progress by printing the refseq ID and gene ID and the number of refseq IDs processed so far
'''### YOUR CODE HERE ###'''

# Note, may need to encode('utf-8')

In [ ]:
#user PrettyTable to display the results
'''### YOUR CODE HERE ###'''

In [ ]:
# Step 4  - merge the refseq_to_gene_id dictionary with the refseq dataframe

# create a new column in the refseq dataframe called 'GeneID'
# fill the column with the gene IDs from the refseq_to_gene_id dictionary
'''### YOUR CODE HERE ###'''

# remove rows with missing values
'''### YOUR CODE HERE ###'''

# display the refseq dataframe
'''### YOUR CODE HERE ###'''

In [ ]:
#Step 7 - combine the gene_symbol and refseq dataframes

# convert the gene_symbol_to_id dictionary to a dataframe
'''### YOUR CODE HERE ###'''

# merge the refseq and gene_symbol_to_id_df dataframes on the 'GeneID' column
'''### YOUR CODE HERE ###'''

# drop the GeneID column
'''### YOUR CODE HERE ###'''

# display the combined dataframe
'''### YOUR CODE HERE ###'''

In [ ]:
#Step 8 - Do some basic summary analysis

# display the number of rows and columns in the combined dataframe
'''### YOUR CODE HERE ###'''

# count how many unique genes are in the combined dataframe
'''### YOUR CODE HERE ###'''

# count how many unique GO terms are in the combined dataframe
'''### YOUR CODE HERE ###'''

# display the number of unique genes and GO terms
'''### YOUR CODE HERE ###'''

# use some plots to visualise the data (up to you!)
'''### YOUR CODE HERE ###'''